// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xnonseq_prefetch.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XNonseq_prefetch_CfgInitialize(XNonseq_prefetch *InstancePtr, XNonseq_prefetch_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Cfg_BaseAddress = ConfigPtr->Cfg_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XNonseq_prefetch_Start(XNonseq_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_AP_CTRL) & 0x80;
    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_AP_CTRL, Data | 0x01);
}

u32 XNonseq_prefetch_IsDone(XNonseq_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XNonseq_prefetch_IsIdle(XNonseq_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XNonseq_prefetch_IsReady(XNonseq_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XNonseq_prefetch_EnableAutoRestart(XNonseq_prefetch *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_AP_CTRL, 0x80);
}

void XNonseq_prefetch_DisableAutoRestart(XNonseq_prefetch *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_AP_CTRL, 0);
}

void XNonseq_prefetch_Set_a(XNonseq_prefetch *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_A_DATA, Data);
}

u32 XNonseq_prefetch_Get_a(XNonseq_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_A_DATA);
    return Data;
}

void XNonseq_prefetch_InterruptGlobalEnable(XNonseq_prefetch *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_GIE, 1);
}

void XNonseq_prefetch_InterruptGlobalDisable(XNonseq_prefetch *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_GIE, 0);
}

void XNonseq_prefetch_InterruptEnable(XNonseq_prefetch *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_IER);
    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_IER, Register | Mask);
}

void XNonseq_prefetch_InterruptDisable(XNonseq_prefetch *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_IER);
    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_IER, Register & (~Mask));
}

void XNonseq_prefetch_InterruptClear(XNonseq_prefetch *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNonseq_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_ISR, Mask);
}

u32 XNonseq_prefetch_InterruptGetEnabled(XNonseq_prefetch *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_IER);
}

u32 XNonseq_prefetch_InterruptGetStatus(XNonseq_prefetch *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNonseq_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XNONSEQ_PREFETCH_CFG_ADDR_ISR);
}

