-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.3
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LL_prefetch is
generic (
    C_M_AXI_A_BUS_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_A_BUS_ID_WIDTH : INTEGER := 1;
    C_M_AXI_A_BUS_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_A_BUS_DATA_WIDTH : INTEGER := 64;
    C_M_AXI_A_BUS_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_A_BUS_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_A_BUS_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_A_BUS_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CFG_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CFG_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_A_BUS_USER_VALUE : INTEGER := 0;
    C_M_AXI_A_BUS_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_A_BUS_PROT_VALUE : INTEGER := 0 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_A_BUS_AWVALID : OUT STD_LOGIC;
    m_axi_A_BUS_AWREADY : IN STD_LOGIC;
    m_axi_A_BUS_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_ADDR_WIDTH-1 downto 0);
    m_axi_A_BUS_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_ID_WIDTH-1 downto 0);
    m_axi_A_BUS_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_A_BUS_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_BUS_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_BUS_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_BUS_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_BUS_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_BUS_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_BUS_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_BUS_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_AWUSER_WIDTH-1 downto 0);
    m_axi_A_BUS_WVALID : OUT STD_LOGIC;
    m_axi_A_BUS_WREADY : IN STD_LOGIC;
    m_axi_A_BUS_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_DATA_WIDTH-1 downto 0);
    m_axi_A_BUS_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_DATA_WIDTH/8-1 downto 0);
    m_axi_A_BUS_WLAST : OUT STD_LOGIC;
    m_axi_A_BUS_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_ID_WIDTH-1 downto 0);
    m_axi_A_BUS_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_WUSER_WIDTH-1 downto 0);
    m_axi_A_BUS_ARVALID : OUT STD_LOGIC;
    m_axi_A_BUS_ARREADY : IN STD_LOGIC;
    m_axi_A_BUS_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_ADDR_WIDTH-1 downto 0);
    m_axi_A_BUS_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_ID_WIDTH-1 downto 0);
    m_axi_A_BUS_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_A_BUS_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_BUS_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_BUS_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_BUS_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_BUS_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_BUS_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_BUS_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_BUS_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_A_BUS_ARUSER_WIDTH-1 downto 0);
    m_axi_A_BUS_RVALID : IN STD_LOGIC;
    m_axi_A_BUS_RREADY : OUT STD_LOGIC;
    m_axi_A_BUS_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_A_BUS_DATA_WIDTH-1 downto 0);
    m_axi_A_BUS_RLAST : IN STD_LOGIC;
    m_axi_A_BUS_RID : IN STD_LOGIC_VECTOR (C_M_AXI_A_BUS_ID_WIDTH-1 downto 0);
    m_axi_A_BUS_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_A_BUS_RUSER_WIDTH-1 downto 0);
    m_axi_A_BUS_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_BUS_BVALID : IN STD_LOGIC;
    m_axi_A_BUS_BREADY : OUT STD_LOGIC;
    m_axi_A_BUS_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_BUS_BID : IN STD_LOGIC_VECTOR (C_M_AXI_A_BUS_ID_WIDTH-1 downto 0);
    m_axi_A_BUS_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_A_BUS_BUSER_WIDTH-1 downto 0);
    s_axi_CFG_AWVALID : IN STD_LOGIC;
    s_axi_CFG_AWREADY : OUT STD_LOGIC;
    s_axi_CFG_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CFG_ADDR_WIDTH-1 downto 0);
    s_axi_CFG_WVALID : IN STD_LOGIC;
    s_axi_CFG_WREADY : OUT STD_LOGIC;
    s_axi_CFG_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CFG_DATA_WIDTH-1 downto 0);
    s_axi_CFG_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CFG_DATA_WIDTH/8-1 downto 0);
    s_axi_CFG_ARVALID : IN STD_LOGIC;
    s_axi_CFG_ARREADY : OUT STD_LOGIC;
    s_axi_CFG_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CFG_ADDR_WIDTH-1 downto 0);
    s_axi_CFG_RVALID : OUT STD_LOGIC;
    s_axi_CFG_RREADY : IN STD_LOGIC;
    s_axi_CFG_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CFG_DATA_WIDTH-1 downto 0);
    s_axi_CFG_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CFG_BVALID : OUT STD_LOGIC;
    s_axi_CFG_BREADY : IN STD_LOGIC;
    s_axi_CFG_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of LL_prefetch is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "LL_prefetch,hls_ip_2016_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=22.380000,HLS_SYN_LAT=78715,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=1183,HLS_SYN_LUT=1458}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (39 downto 0) := "0000000001000000000000000000000000000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (39 downto 0) := "0000000010000000000000000000000000000000";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (39 downto 0) := "0000000100000000000000000000000000000000";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (39 downto 0) := "0000001000000000000000000000000000000000";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (39 downto 0) := "0000010000000000000000000000000000000000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (39 downto 0) := "0000100000000000000000000000000000000000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (39 downto 0) := "0001000000000000000000000000000000000000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (39 downto 0) := "0010000000000000000000000000000000000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (39 downto 0) := "0100000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (39 downto 0) := "1000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv9_19 : STD_LOGIC_VECTOR (8 downto 0) := "000011001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv9_1F4 : STD_LOGIC_VECTOR (8 downto 0) := "111110100";
    constant ap_const_lv14_2341 : STD_LOGIC_VECTOR (13 downto 0) := "10001101000001";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal a : STD_LOGIC_VECTOR (31 downto 0);
    signal A_BUS_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal A_BUS_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state22 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal ap_CS_fsm_state24 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal ap_CS_fsm_state31 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state31 : signal is "none";
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal exitcond_flatten_reg_502 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal A_BUS_AWREADY : STD_LOGIC;
    signal A_BUS_WREADY : STD_LOGIC;
    signal A_BUS_ARVALID : STD_LOGIC;
    signal A_BUS_ARREADY : STD_LOGIC;
    signal A_BUS_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal A_BUS_RVALID : STD_LOGIC;
    signal A_BUS_RREADY : STD_LOGIC;
    signal A_BUS_RDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal A_BUS_RLAST : STD_LOGIC;
    signal A_BUS_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal A_BUS_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal A_BUS_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal A_BUS_BVALID : STD_LOGIC;
    signal A_BUS_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal A_BUS_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal A_BUS_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_169 : STD_LOGIC_VECTOR (13 downto 0);
    signal i2_reg_180 : STD_LOGIC_VECTOR (8 downto 0);
    signal reg_211 : STD_LOGIC_VECTOR (15 downto 0);
    signal a1_reg_411 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_1_fu_225_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_417 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_ioackin_A_BUS_ARREADY : STD_LOGIC;
    signal tmp_1_cast1_fu_235_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_1_cast1_reg_429 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal skip_cum_offs_cast_fu_238_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal a2_sum_fu_271_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal a2_sum_reg_449 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal exitcond3_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a2_sum3_fu_276_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal a2_sum3_reg_454 : STD_LOGIC_VECTOR (30 downto 0);
    signal i_1_fu_281_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_1_reg_459 : STD_LOGIC_VECTOR (8 downto 0);
    signal a2_sum4_fu_287_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal a2_sum4_reg_464 : STD_LOGIC_VECTOR (30 downto 0);
    signal A_BUS_addr_2_reg_469 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_BUS_addr_3_reg_475 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_201_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_offs_load_new_reg_481 : STD_LOGIC_VECTOR (15 downto 0);
    signal cum_offs_3_fu_315_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal cum_offs_3_reg_486 : STD_LOGIC_VECTOR (24 downto 0);
    signal skip_cum_offs_3_1_fu_325_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal exitcond_flatten_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_next_fu_347_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal indvar_flatten_next_reg_506 : STD_LOGIC_VECTOR (13 downto 0);
    signal buff_addr_2_reg_511 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter1_buff_addr_2_reg_511 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_2_fu_372_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_2_reg_517 : STD_LOGIC_VECTOR (8 downto 0);
    signal buff_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_load_reg_522 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2_sum5_fu_378_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2_sum5_reg_527 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal buff_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buff_ce0 : STD_LOGIC;
    signal buff_we0 : STD_LOGIC;
    signal buff_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal buff_ce1 : STD_LOGIC;
    signal buff_we1 : STD_LOGIC;
    signal buff_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_reg_136 : STD_LOGIC_VECTOR (8 downto 0);
    signal skip_cum_offs1_reg_147 : STD_LOGIC_VECTOR (24 downto 0);
    signal cum_offs_reg_157 : STD_LOGIC_VECTOR (24 downto 0);
    signal indvar_flatten_phi_fu_173_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal i2_phi_fu_184_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_cast2_fu_242_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal i2_cast1_fu_367_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2_sum_cast_fu_292_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2_sum3_cast_fu_302_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2_sum4_cast_fu_331_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2_sum6_fu_399_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_ioackin_A_BUS_ARREADY : STD_LOGIC := '0';
    signal skip_cum_offs1_cast_fu_247_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal seq_skip_offs_fu_393_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cum_offs_cast7_cast_fu_267_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal skip_cum_offs1_cast_s_fu_252_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_1_cast_fu_312_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_3_1_cast_fu_321_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal exitcond9_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i2_mid2_fu_359_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_6_fu_389_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state49 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state49 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_condition_210 : BOOLEAN;
    signal ap_condition_567 : BOOLEAN;

    component LL_prefetch_buff IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LL_prefetch_CFG_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        a : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LL_prefetch_A_BUS_m_axi IS
    generic (
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    LL_prefetch_CFG_s_axi_U : component LL_prefetch_CFG_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CFG_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CFG_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CFG_AWVALID,
        AWREADY => s_axi_CFG_AWREADY,
        AWADDR => s_axi_CFG_AWADDR,
        WVALID => s_axi_CFG_WVALID,
        WREADY => s_axi_CFG_WREADY,
        WDATA => s_axi_CFG_WDATA,
        WSTRB => s_axi_CFG_WSTRB,
        ARVALID => s_axi_CFG_ARVALID,
        ARREADY => s_axi_CFG_ARREADY,
        ARADDR => s_axi_CFG_ARADDR,
        RVALID => s_axi_CFG_RVALID,
        RREADY => s_axi_CFG_RREADY,
        RDATA => s_axi_CFG_RDATA,
        RRESP => s_axi_CFG_RRESP,
        BVALID => s_axi_CFG_BVALID,
        BREADY => s_axi_CFG_BREADY,
        BRESP => s_axi_CFG_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        a => a);

    LL_prefetch_A_BUS_m_axi_U : component LL_prefetch_A_BUS_m_axi
    generic map (
        USER_DW => 64,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_A_BUS_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_A_BUS_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_A_BUS_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_A_BUS_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_A_BUS_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_A_BUS_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_A_BUS_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_A_BUS_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_A_BUS_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_A_BUS_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_A_BUS_CACHE_VALUE)
    port map (
        AWVALID => m_axi_A_BUS_AWVALID,
        AWREADY => m_axi_A_BUS_AWREADY,
        AWADDR => m_axi_A_BUS_AWADDR,
        AWID => m_axi_A_BUS_AWID,
        AWLEN => m_axi_A_BUS_AWLEN,
        AWSIZE => m_axi_A_BUS_AWSIZE,
        AWBURST => m_axi_A_BUS_AWBURST,
        AWLOCK => m_axi_A_BUS_AWLOCK,
        AWCACHE => m_axi_A_BUS_AWCACHE,
        AWPROT => m_axi_A_BUS_AWPROT,
        AWQOS => m_axi_A_BUS_AWQOS,
        AWREGION => m_axi_A_BUS_AWREGION,
        AWUSER => m_axi_A_BUS_AWUSER,
        WVALID => m_axi_A_BUS_WVALID,
        WREADY => m_axi_A_BUS_WREADY,
        WDATA => m_axi_A_BUS_WDATA,
        WSTRB => m_axi_A_BUS_WSTRB,
        WLAST => m_axi_A_BUS_WLAST,
        WID => m_axi_A_BUS_WID,
        WUSER => m_axi_A_BUS_WUSER,
        ARVALID => m_axi_A_BUS_ARVALID,
        ARREADY => m_axi_A_BUS_ARREADY,
        ARADDR => m_axi_A_BUS_ARADDR,
        ARID => m_axi_A_BUS_ARID,
        ARLEN => m_axi_A_BUS_ARLEN,
        ARSIZE => m_axi_A_BUS_ARSIZE,
        ARBURST => m_axi_A_BUS_ARBURST,
        ARLOCK => m_axi_A_BUS_ARLOCK,
        ARCACHE => m_axi_A_BUS_ARCACHE,
        ARPROT => m_axi_A_BUS_ARPROT,
        ARQOS => m_axi_A_BUS_ARQOS,
        ARREGION => m_axi_A_BUS_ARREGION,
        ARUSER => m_axi_A_BUS_ARUSER,
        RVALID => m_axi_A_BUS_RVALID,
        RREADY => m_axi_A_BUS_RREADY,
        RDATA => m_axi_A_BUS_RDATA,
        RLAST => m_axi_A_BUS_RLAST,
        RID => m_axi_A_BUS_RID,
        RUSER => m_axi_A_BUS_RUSER,
        RRESP => m_axi_A_BUS_RRESP,
        BVALID => m_axi_A_BUS_BVALID,
        BREADY => m_axi_A_BUS_BREADY,
        BRESP => m_axi_A_BUS_BRESP,
        BID => m_axi_A_BUS_BID,
        BUSER => m_axi_A_BUS_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => A_BUS_ARVALID,
        I_ARREADY => A_BUS_ARREADY,
        I_ARADDR => A_BUS_ARADDR,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_1,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => A_BUS_RVALID,
        I_RREADY => A_BUS_RREADY,
        I_RDATA => A_BUS_RDATA,
        I_RID => A_BUS_RID,
        I_RUSER => A_BUS_RUSER,
        I_RRESP => A_BUS_RRESP,
        I_RLAST => A_BUS_RLAST,
        I_AWVALID => ap_const_logic_0,
        I_AWREADY => A_BUS_AWREADY,
        I_AWADDR => ap_const_lv32_0,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_0,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => ap_const_logic_0,
        I_WREADY => A_BUS_WREADY,
        I_WDATA => ap_const_lv64_0,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv8_0,
        I_BVALID => A_BUS_BVALID,
        I_BREADY => ap_const_logic_0,
        I_BRESP => A_BUS_BRESP,
        I_BID => A_BUS_BID,
        I_BUSER => A_BUS_BUSER);

    buff_U : component LL_prefetch_buff
    generic map (
        DataWidth => 32,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => buff_address0,
        ce0 => buff_ce0,
        we0 => buff_we0,
        d0 => buff_d0,
        q0 => buff_q0,
        address1 => buff_address1,
        ce1 => buff_ce1,
        we1 => buff_we1,
        d1 => buff_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))) and not((ap_const_lv1_0 = exitcond_flatten_fu_341_p2)))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_lv1_1 = ap_CS_fsm_state31) and not((A_BUS_RVALID = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                elsif ((((ap_const_lv1_1 = ap_CS_fsm_state31) and not((A_BUS_RVALID = ap_const_logic_0))) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage7) and not((exitcond_flatten_reg_502 = ap_const_lv1_0))))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage7)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_lv1_1 = ap_CS_fsm_state31) and not((A_BUS_RVALID = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_A_BUS_ARREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_A_BUS_ARREADY <= ap_const_logic_0;
            else
                if ((((ap_const_lv1_1 = ap_CS_fsm_state2) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) or ((ap_const_lv1_1 = ap_CS_fsm_state12) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) or ((ap_const_lv1_1 = ap_CS_fsm_state14) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) or ((ap_const_lv1_1 = ap_CS_fsm_state24) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) or ((ap_const_lv1_1 = ap_CS_fsm_state13) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) or ((ap_const_lv1_1 = ap_CS_fsm_state15) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_reg_502 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))))))) then 
                    ap_reg_ioackin_A_BUS_ARREADY <= ap_const_logic_0;
                elsif ((((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_logic_1 = A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state12) and (ap_const_logic_1 = A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state13) and (ap_const_logic_1 = A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state14) and (ap_const_logic_1 = A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state15) and (ap_const_logic_1 = A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state24) and (ap_const_logic_1 = A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_logic_1 = A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = A_BUS_ARREADY) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)))))) then 
                    ap_reg_ioackin_A_BUS_ARREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    cum_offs_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state23))) then 
                cum_offs_reg_157 <= cum_offs_3_reg_486;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state10))) then 
                cum_offs_reg_157 <= ap_const_lv25_0;
            end if; 
        end if;
    end process;

    i2_reg_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))))) then 
                i2_reg_180 <= i_2_reg_517;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state31) and not((A_BUS_RVALID = ap_const_logic_0)))) then 
                i2_reg_180 <= ap_const_lv9_19;
            end if; 
        end if;
    end process;

    i_reg_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state23))) then 
                i_reg_136 <= i_1_reg_459;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state10))) then 
                i_reg_136 <= ap_const_lv9_1;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_169_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))))) then 
                indvar_flatten_reg_169 <= indvar_flatten_next_reg_506;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state31) and not((A_BUS_RVALID = ap_const_logic_0)))) then 
                indvar_flatten_reg_169 <= ap_const_lv14_0;
            end if; 
        end if;
    end process;

    skip_cum_offs1_reg_147_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state23))) then 
                skip_cum_offs1_reg_147 <= skip_cum_offs_3_1_fu_325_p2;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state10))) then 
                skip_cum_offs1_reg_147 <= skip_cum_offs_cast_fu_238_p1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state12) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))) then
                A_BUS_addr_2_reg_469 <= a2_sum_cast_fu_292_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state14) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))) then
                A_BUS_addr_3_reg_475 <= a2_sum3_cast_fu_302_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then
                a1_reg_411 <= a(31 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state11) and (ap_const_lv1_0 = exitcond3_fu_256_p2))) then
                a2_sum3_reg_454 <= a2_sum3_fu_276_p2;
                a2_sum_reg_449 <= a2_sum_fu_271_p2;
                i_1_reg_459 <= i_1_fu_281_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state11) and not((ap_const_lv1_0 = exitcond3_fu_256_p2)))) then
                a2_sum4_reg_464 <= a2_sum4_fu_287_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))))))) then
                a2_sum5_reg_527 <= a2_sum5_fu_378_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state20) and not((A_BUS_RVALID = ap_const_logic_0)))) then
                a_offs_load_new_reg_481 <= A_BUS_RDATA(47 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))))) then
                ap_pipeline_reg_pp0_iter1_buff_addr_2_reg_511 <= buff_addr_2_reg_511;
                ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502 <= exitcond_flatten_reg_502;
                exitcond_flatten_reg_502 <= exitcond_flatten_fu_341_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))) and (ap_const_lv1_0 = exitcond_flatten_fu_341_p2))) then
                buff_addr_2_reg_511 <= i2_cast1_fu_367_p1(9 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))))))) then
                buff_load_reg_522 <= buff_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state21) and not((A_BUS_RVALID = ap_const_logic_0)))) then
                cum_offs_3_reg_486 <= cum_offs_3_fu_315_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))) and (ap_const_lv1_0 = exitcond_flatten_fu_341_p2))) then
                i_2_reg_517 <= i_2_fu_372_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))))) then
                indvar_flatten_next_reg_506 <= indvar_flatten_next_fu_347_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_lv1_1 = ap_CS_fsm_state9) and not((A_BUS_RVALID = ap_const_logic_0))) or ((ap_const_lv1_1 = ap_CS_fsm_state22) and not((A_BUS_RVALID = ap_const_logic_0))))) then
                reg_211 <= A_BUS_RDATA(63 downto 48);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state10))) then
                    tmp_1_cast1_reg_429(28 downto 0) <= tmp_1_cast1_fu_235_p1(28 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state2) and not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))) then
                    tmp_1_reg_417(28 downto 0) <= tmp_1_fu_225_p1(28 downto 0);
            end if;
        end if;
    end process;
    tmp_1_reg_417(31 downto 29) <= "000";
    tmp_1_cast1_reg_429(30 downto 29) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_enable_reg_pp0_iter0, exitcond_flatten_reg_502, ap_enable_reg_pp0_iter1, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, A_BUS_RVALID, ap_sig_ioackin_A_BUS_ARREADY, exitcond3_fu_256_p2, exitcond_flatten_fu_341_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (not((A_BUS_RVALID = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (not((ap_const_lv1_0 = exitcond3_fu_256_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state24;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state12 => 
                if (not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                if (not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if (not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                if (not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                if (not((A_BUS_RVALID = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state20 => 
                if (not((A_BUS_RVALID = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state21 => 
                if (not((A_BUS_RVALID = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state21;
                end if;
            when ap_ST_fsm_state22 => 
                if (not((A_BUS_RVALID = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_state22;
                end if;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state24 => 
                if (not((ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY))) then
                    ap_NS_fsm <= ap_ST_fsm_state25;
                else
                    ap_NS_fsm <= ap_ST_fsm_state24;
                end if;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                if (not((A_BUS_RVALID = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state31;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))) and not(((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter1)))) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))) and not((ap_const_lv1_0 = exitcond_flatten_fu_341_p2)) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter1)))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif ((((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter1))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0))) and not((ap_const_lv1_0 = exitcond_flatten_fu_341_p2)) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter1))))) then
                    ap_NS_fsm <= ap_ST_fsm_state49;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
            when ap_ST_fsm_pp0_stage4 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
            when ap_ST_fsm_pp0_stage5 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
            when ap_ST_fsm_pp0_stage6 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
            when ap_ST_fsm_pp0_stage7 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;

    A_BUS_ARADDR_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state24, tmp_1_fu_225_p1, A_BUS_addr_2_reg_469, A_BUS_addr_3_reg_475, a2_sum5_reg_527, a2_sum_cast_fu_292_p1, a2_sum3_cast_fu_302_p1, a2_sum4_cast_fu_331_p1, a2_sum6_fu_399_p2, ap_reg_ioackin_A_BUS_ARREADY, ap_condition_210, ap_condition_567)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) then
            if ((ap_condition_567 = ap_const_boolean_1)) then 
                A_BUS_ARADDR <= a2_sum6_fu_399_p2;
            elsif ((ap_condition_210 = ap_const_boolean_1)) then 
                A_BUS_ARADDR <= a2_sum5_reg_527;
            elsif ((ap_const_lv1_1 = ap_CS_fsm_state24)) then 
                A_BUS_ARADDR <= a2_sum4_cast_fu_331_p1;
            elsif ((ap_const_lv1_1 = ap_CS_fsm_state15)) then 
                A_BUS_ARADDR <= A_BUS_addr_3_reg_475;
            elsif ((ap_const_lv1_1 = ap_CS_fsm_state14)) then 
                A_BUS_ARADDR <= a2_sum3_cast_fu_302_p1;
            elsif ((ap_const_lv1_1 = ap_CS_fsm_state13)) then 
                A_BUS_ARADDR <= A_BUS_addr_2_reg_469;
            elsif ((ap_const_lv1_1 = ap_CS_fsm_state12)) then 
                A_BUS_ARADDR <= a2_sum_cast_fu_292_p1;
            elsif ((ap_const_lv1_1 = ap_CS_fsm_state2)) then 
                A_BUS_ARADDR <= tmp_1_fu_225_p1;
            else 
                A_BUS_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            A_BUS_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    A_BUS_ARVALID_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state24, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0, exitcond_flatten_reg_502, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502, A_BUS_RVALID, ap_reg_ioackin_A_BUS_ARREADY)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state12) and (ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state13) and (ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state14) and (ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state15) and (ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_state24) and (ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)))))) then 
            A_BUS_ARVALID <= ap_const_logic_1;
        else 
            A_BUS_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    A_BUS_RREADY_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22, ap_CS_fsm_state31, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, A_BUS_RVALID, ap_sig_ioackin_A_BUS_ARREADY)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state9) and not((A_BUS_RVALID = ap_const_logic_0))) or ((ap_const_lv1_1 = ap_CS_fsm_state22) and not((A_BUS_RVALID = ap_const_logic_0))) or ((ap_const_lv1_1 = ap_CS_fsm_state20) and not((A_BUS_RVALID = ap_const_logic_0))) or ((ap_const_lv1_1 = ap_CS_fsm_state21) and not((A_BUS_RVALID = ap_const_logic_0))) or ((ap_const_lv1_1 = ap_CS_fsm_state31) and not((A_BUS_RVALID = ap_const_logic_0))) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))))) or ((ap_const_lv1_1 = ap_CS_fsm_state19) and not((A_BUS_RVALID = ap_const_logic_0))) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0)))))) then 
            A_BUS_RREADY <= ap_const_logic_1;
        else 
            A_BUS_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    A_BUS_blk_n_AR_assign_proc : process(m_axi_A_BUS_ARREADY, ap_CS_fsm_state2, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state24, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0, exitcond_flatten_reg_502, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state2)) or ((ap_const_lv1_1 = ap_CS_fsm_state12)) or ((ap_const_lv1_1 = ap_CS_fsm_state13)) or ((ap_const_lv1_1 = ap_CS_fsm_state14)) or ((ap_const_lv1_1 = ap_CS_fsm_state15)) or ((ap_const_lv1_1 = ap_CS_fsm_state24)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_reg_502 = ap_const_lv1_0)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502)))) then 
            A_BUS_blk_n_AR <= m_axi_A_BUS_ARREADY;
        else 
            A_BUS_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    A_BUS_blk_n_R_assign_proc : process(m_axi_A_BUS_RVALID, ap_CS_fsm_state9, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22, ap_CS_fsm_state31, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state9)) or ((ap_const_lv1_1 = ap_CS_fsm_state19)) or ((ap_const_lv1_1 = ap_CS_fsm_state20)) or ((ap_const_lv1_1 = ap_CS_fsm_state21)) or ((ap_const_lv1_1 = ap_CS_fsm_state22)) or ((ap_const_lv1_1 = ap_CS_fsm_state31)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502)) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2)))) then 
            A_BUS_blk_n_R <= m_axi_A_BUS_RVALID;
        else 
            A_BUS_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

        a2_sum3_cast_fu_302_p1 <= std_logic_vector(resize(signed(a2_sum3_reg_454),32));

    a2_sum3_fu_276_p2 <= std_logic_vector(signed(skip_cum_offs1_cast_s_fu_252_p1) + signed(tmp_1_cast1_reg_429));
        a2_sum4_cast_fu_331_p1 <= std_logic_vector(resize(signed(a2_sum4_reg_464),32));

    a2_sum4_fu_287_p2 <= std_logic_vector(unsigned(tmp_1_cast1_reg_429) + unsigned(skip_cum_offs1_cast_s_fu_252_p1));
    a2_sum5_fu_378_p2 <= std_logic_vector(unsigned(tmp_1_reg_417) + unsigned(buff_q0));
    a2_sum6_fu_399_p2 <= std_logic_vector(unsigned(tmp_1_reg_417) + unsigned(seq_skip_offs_fu_393_p2));
        a2_sum_cast_fu_292_p1 <= std_logic_vector(resize(signed(a2_sum_reg_449),32));

    a2_sum_fu_271_p2 <= std_logic_vector(signed(cum_offs_cast7_cast_fu_267_p1) + signed(tmp_1_cast1_reg_429));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(31 downto 31);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(32 downto 32);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(33 downto 33);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(38 downto 38);
    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9 downto 9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10 downto 10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11 downto 11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12 downto 12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13 downto 13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14 downto 14);
    ap_CS_fsm_state19 <= ap_CS_fsm(18 downto 18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1 downto 1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19 downto 19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20 downto 20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21 downto 21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22 downto 22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23 downto 23);
    ap_CS_fsm_state31 <= ap_CS_fsm(30 downto 30);
    ap_CS_fsm_state49 <= ap_CS_fsm(39 downto 39);
    ap_CS_fsm_state9 <= ap_CS_fsm(8 downto 8);

    ap_condition_210_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0, exitcond_flatten_reg_502)
    begin
                ap_condition_210 <= ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_reg_502 = ap_const_lv1_0));
    end process;


    ap_condition_567_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502, A_BUS_RVALID)
    begin
                ap_condition_567 <= ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0))));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state49)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state49))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state49)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state49))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_ioackin_A_BUS_ARREADY_assign_proc : process(A_BUS_ARREADY, ap_reg_ioackin_A_BUS_ARREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_A_BUS_ARREADY)) then 
            ap_sig_ioackin_A_BUS_ARREADY <= A_BUS_ARREADY;
        else 
            ap_sig_ioackin_A_BUS_ARREADY <= ap_const_logic_1;
        end if; 
    end process;


    buff_address0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage0, ap_CS_fsm_state11, i2_cast1_fu_367_p1)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_address0 <= i2_cast1_fu_367_p1(9 - 1 downto 0);
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state11))) then 
            buff_address0 <= ap_const_lv32_0(9 - 1 downto 0);
        else 
            buff_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    buff_address1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_CS_fsm_state11, ap_pipeline_reg_pp0_iter1_buff_addr_2_reg_511, i_cast2_fu_242_p1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
            buff_address1 <= ap_pipeline_reg_pp0_iter1_buff_addr_2_reg_511;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state11))) then 
            buff_address1 <= i_cast2_fu_242_p1(9 - 1 downto 0);
        else 
            buff_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    buff_ce0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, A_BUS_RVALID, ap_CS_fsm_state11)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state11)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not(((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (A_BUS_RVALID = ap_const_logic_0)))))) then 
            buff_ce0 <= ap_const_logic_1;
        else 
            buff_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_ce1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502, A_BUS_RVALID, ap_sig_ioackin_A_BUS_ARREADY, ap_CS_fsm_state11)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state11)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))))))) then 
            buff_ce1 <= ap_const_logic_1;
        else 
            buff_ce1 <= ap_const_logic_0;
        end if; 
    end process;

        buff_d0 <= std_logic_vector(resize(signed(cum_offs_reg_157),32));


    buff_d1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_CS_fsm_state11, skip_cum_offs1_cast_fu_247_p1, seq_skip_offs_fu_393_p2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
            buff_d1 <= seq_skip_offs_fu_393_p2;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state11))) then 
            buff_d1 <= skip_cum_offs1_cast_fu_247_p1;
        else 
            buff_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buff_we0_assign_proc : process(ap_CS_fsm_state11, exitcond3_fu_256_p2)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state11) and (ap_const_lv1_0 = exitcond3_fu_256_p2)))) then 
            buff_we0 <= ap_const_logic_1;
        else 
            buff_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_we1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502, A_BUS_RVALID, ap_sig_ioackin_A_BUS_ARREADY, ap_CS_fsm_state11, exitcond3_fu_256_p2)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state11) and (ap_const_lv1_0 = exitcond3_fu_256_p2)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (A_BUS_RVALID = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_502) and (ap_const_logic_0 = ap_sig_ioackin_A_BUS_ARREADY)))))))) then 
            buff_we1 <= ap_const_logic_1;
        else 
            buff_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cum_offs_3_fu_315_p2 <= std_logic_vector(unsigned(cum_offs_reg_157) + unsigned(tmp_1_cast_fu_312_p1));
        cum_offs_cast7_cast_fu_267_p1 <= std_logic_vector(resize(signed(cum_offs_reg_157),31));

    exitcond3_fu_256_p2 <= "1" when (i_reg_136 = ap_const_lv9_1F4) else "0";
    exitcond9_fu_353_p2 <= "1" when (i2_phi_fu_184_p4 = ap_const_lv9_1F4) else "0";
    exitcond_flatten_fu_341_p2 <= "1" when (indvar_flatten_phi_fu_173_p4 = ap_const_lv14_2341) else "0";
    grp_fu_201_p4 <= A_BUS_RDATA(47 downto 32);
    i2_cast1_fu_367_p1 <= std_logic_vector(resize(unsigned(i2_mid2_fu_359_p3),32));
    i2_mid2_fu_359_p3 <= 
        ap_const_lv9_19 when (exitcond9_fu_353_p2(0) = '1') else 
        i2_phi_fu_184_p4;

    i2_phi_fu_184_p4_assign_proc : process(exitcond_flatten_reg_502, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage0, i2_reg_180, i_2_reg_517)
    begin
        if (((exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0))) then 
            i2_phi_fu_184_p4 <= i_2_reg_517;
        else 
            i2_phi_fu_184_p4 <= i2_reg_180;
        end if; 
    end process;

    i_1_fu_281_p2 <= std_logic_vector(unsigned(i_reg_136) + unsigned(ap_const_lv9_1));
    i_2_fu_372_p2 <= std_logic_vector(unsigned(i2_mid2_fu_359_p3) + unsigned(ap_const_lv9_1));
    i_cast2_fu_242_p1 <= std_logic_vector(resize(unsigned(i_reg_136),32));
    indvar_flatten_next_fu_347_p2 <= std_logic_vector(unsigned(indvar_flatten_phi_fu_173_p4) + unsigned(ap_const_lv14_1));

    indvar_flatten_phi_fu_173_p4_assign_proc : process(exitcond_flatten_reg_502, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage0, indvar_flatten_reg_169, indvar_flatten_next_reg_506)
    begin
        if (((exitcond_flatten_reg_502 = ap_const_lv1_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage0))) then 
            indvar_flatten_phi_fu_173_p4 <= indvar_flatten_next_reg_506;
        else 
            indvar_flatten_phi_fu_173_p4 <= indvar_flatten_reg_169;
        end if; 
    end process;

    seq_skip_offs_fu_393_p2 <= std_logic_vector(unsigned(buff_load_reg_522) + unsigned(tmp_6_fu_389_p1));
        skip_cum_offs1_cast_fu_247_p1 <= std_logic_vector(resize(signed(skip_cum_offs1_reg_147),32));

        skip_cum_offs1_cast_s_fu_252_p1 <= std_logic_vector(resize(signed(skip_cum_offs1_reg_147),31));

    skip_cum_offs_3_1_fu_325_p2 <= std_logic_vector(unsigned(skip_cum_offs1_reg_147) + unsigned(tmp_3_1_cast_fu_321_p1));
        skip_cum_offs_cast_fu_238_p1 <= std_logic_vector(resize(signed(reg_211),25));

    tmp_1_cast1_fu_235_p1 <= std_logic_vector(resize(unsigned(a1_reg_411),31));
        tmp_1_cast_fu_312_p1 <= std_logic_vector(resize(signed(a_offs_load_new_reg_481),25));

    tmp_1_fu_225_p1 <= std_logic_vector(resize(unsigned(a1_reg_411),32));
        tmp_3_1_cast_fu_321_p1 <= std_logic_vector(resize(signed(reg_211),25));

        tmp_6_fu_389_p1 <= std_logic_vector(resize(signed(grp_fu_201_p4),32));

end behav;
