// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XFETCH_LOG_H
#define XFETCH_LOG_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xfetch_log_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XFetch_log_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XFetch_log;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XFetch_log_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XFetch_log_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XFetch_log_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XFetch_log_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XFetch_log_Initialize(XFetch_log *InstancePtr, u16 DeviceId);
XFetch_log_Config* XFetch_log_LookupConfig(u16 DeviceId);
int XFetch_log_CfgInitialize(XFetch_log *InstancePtr, XFetch_log_Config *ConfigPtr);
#else
int XFetch_log_Initialize(XFetch_log *InstancePtr, const char* InstanceName);
int XFetch_log_Release(XFetch_log *InstancePtr);
#endif

void XFetch_log_Start(XFetch_log *InstancePtr);
u32 XFetch_log_IsDone(XFetch_log *InstancePtr);
u32 XFetch_log_IsIdle(XFetch_log *InstancePtr);
u32 XFetch_log_IsReady(XFetch_log *InstancePtr);
void XFetch_log_EnableAutoRestart(XFetch_log *InstancePtr);
void XFetch_log_DisableAutoRestart(XFetch_log *InstancePtr);
u32 XFetch_log_Get_return(XFetch_log *InstancePtr);

void XFetch_log_Set_a(XFetch_log *InstancePtr, u32 Data);
u32 XFetch_log_Get_a(XFetch_log *InstancePtr);
void XFetch_log_Set_log(XFetch_log *InstancePtr, u32 Data);
u32 XFetch_log_Get_log(XFetch_log *InstancePtr);

void XFetch_log_InterruptGlobalEnable(XFetch_log *InstancePtr);
void XFetch_log_InterruptGlobalDisable(XFetch_log *InstancePtr);
void XFetch_log_InterruptEnable(XFetch_log *InstancePtr, u32 Mask);
void XFetch_log_InterruptDisable(XFetch_log *InstancePtr, u32 Mask);
void XFetch_log_InterruptClear(XFetch_log *InstancePtr, u32 Mask);
u32 XFetch_log_InterruptGetEnabled(XFetch_log *InstancePtr);
u32 XFetch_log_InterruptGetStatus(XFetch_log *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
