// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSKIP_LIST_PREFETCH_H
#define XSKIP_LIST_PREFETCH_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xskip_list_prefetch_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Cfg_BaseAddress;
} XSkip_list_prefetch_Config;
#endif

typedef struct {
    u32 Cfg_BaseAddress;
    u32 IsReady;
} XSkip_list_prefetch;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSkip_list_prefetch_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSkip_list_prefetch_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSkip_list_prefetch_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSkip_list_prefetch_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSkip_list_prefetch_Initialize(XSkip_list_prefetch *InstancePtr, u16 DeviceId);
XSkip_list_prefetch_Config* XSkip_list_prefetch_LookupConfig(u16 DeviceId);
int XSkip_list_prefetch_CfgInitialize(XSkip_list_prefetch *InstancePtr, XSkip_list_prefetch_Config *ConfigPtr);
#else
int XSkip_list_prefetch_Initialize(XSkip_list_prefetch *InstancePtr, const char* InstanceName);
int XSkip_list_prefetch_Release(XSkip_list_prefetch *InstancePtr);
#endif

void XSkip_list_prefetch_Start(XSkip_list_prefetch *InstancePtr);
u32 XSkip_list_prefetch_IsDone(XSkip_list_prefetch *InstancePtr);
u32 XSkip_list_prefetch_IsIdle(XSkip_list_prefetch *InstancePtr);
u32 XSkip_list_prefetch_IsReady(XSkip_list_prefetch *InstancePtr);
void XSkip_list_prefetch_EnableAutoRestart(XSkip_list_prefetch *InstancePtr);
void XSkip_list_prefetch_DisableAutoRestart(XSkip_list_prefetch *InstancePtr);

void XSkip_list_prefetch_Set_a(XSkip_list_prefetch *InstancePtr, u32 Data);
u32 XSkip_list_prefetch_Get_a(XSkip_list_prefetch *InstancePtr);

void XSkip_list_prefetch_InterruptGlobalEnable(XSkip_list_prefetch *InstancePtr);
void XSkip_list_prefetch_InterruptGlobalDisable(XSkip_list_prefetch *InstancePtr);
void XSkip_list_prefetch_InterruptEnable(XSkip_list_prefetch *InstancePtr, u32 Mask);
void XSkip_list_prefetch_InterruptDisable(XSkip_list_prefetch *InstancePtr, u32 Mask);
void XSkip_list_prefetch_InterruptClear(XSkip_list_prefetch *InstancePtr, u32 Mask);
u32 XSkip_list_prefetch_InterruptGetEnabled(XSkip_list_prefetch *InstancePtr);
u32 XSkip_list_prefetch_InterruptGetStatus(XSkip_list_prefetch *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
