// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xskip_list_prefetch.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSkip_list_prefetch_CfgInitialize(XSkip_list_prefetch *InstancePtr, XSkip_list_prefetch_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Cfg_BaseAddress = ConfigPtr->Cfg_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSkip_list_prefetch_Start(XSkip_list_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_AP_CTRL) & 0x80;
    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSkip_list_prefetch_IsDone(XSkip_list_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSkip_list_prefetch_IsIdle(XSkip_list_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSkip_list_prefetch_IsReady(XSkip_list_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSkip_list_prefetch_EnableAutoRestart(XSkip_list_prefetch *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_AP_CTRL, 0x80);
}

void XSkip_list_prefetch_DisableAutoRestart(XSkip_list_prefetch *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_AP_CTRL, 0);
}

void XSkip_list_prefetch_Set_a(XSkip_list_prefetch *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_A_DATA, Data);
}

u32 XSkip_list_prefetch_Get_a(XSkip_list_prefetch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_A_DATA);
    return Data;
}

void XSkip_list_prefetch_InterruptGlobalEnable(XSkip_list_prefetch *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_GIE, 1);
}

void XSkip_list_prefetch_InterruptGlobalDisable(XSkip_list_prefetch *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_GIE, 0);
}

void XSkip_list_prefetch_InterruptEnable(XSkip_list_prefetch *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_IER);
    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_IER, Register | Mask);
}

void XSkip_list_prefetch_InterruptDisable(XSkip_list_prefetch *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_IER);
    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_IER, Register & (~Mask));
}

void XSkip_list_prefetch_InterruptClear(XSkip_list_prefetch *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSkip_list_prefetch_WriteReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_ISR, Mask);
}

u32 XSkip_list_prefetch_InterruptGetEnabled(XSkip_list_prefetch *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_IER);
}

u32 XSkip_list_prefetch_InterruptGetStatus(XSkip_list_prefetch *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSkip_list_prefetch_ReadReg(InstancePtr->Cfg_BaseAddress, XSKIP_LIST_PREFETCH_CFG_ADDR_ISR);
}

