// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xlink_list.h"

extern XLink_list_Config XLink_list_ConfigTable[];

XLink_list_Config *XLink_list_LookupConfig(u16 DeviceId) {
	XLink_list_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XLINK_LIST_NUM_INSTANCES; Index++) {
		if (XLink_list_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XLink_list_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XLink_list_Initialize(XLink_list *InstancePtr, u16 DeviceId) {
	XLink_list_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XLink_list_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XLink_list_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

