// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "SOURCE_BUS"
#define AUTOTB_TVIN_SOURCE_BUS  "../tv/cdatafile/c.read_ocm.autotvin_SOURCE_BUS.dat"
#define AUTOTB_TVOUT_SOURCE_BUS  "../tv/cdatafile/c.read_ocm.autotvout_SOURCE_BUS.dat"
// wrapc file define: "source"
#define AUTOTB_TVIN_source  "../tv/cdatafile/c.read_ocm.autotvin_source.dat"
// wrapc file define: "start"
#define AUTOTB_TVIN_start  "../tv/cdatafile/c.read_ocm.autotvin_start.dat"
// wrapc file define: "ap_return"
#define AUTOTB_TVOUT_ap_return  "../tv/cdatafile/c.read_ocm.autotvout_ap_return.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "SOURCE_BUS"
#define AUTOTB_TVOUT_PC_SOURCE_BUS  "../tv/rtldatafile/rtl.read_ocm.autotvout_SOURCE_BUS.dat"
// tvout file define: "ap_return"
#define AUTOTB_TVOUT_PC_ap_return  "../tv/rtldatafile/rtl.read_ocm.autotvout_ap_return.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			SOURCE_BUS_depth = 0;
			source_depth = 0;
			start_depth = 0;
			ap_return_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{SOURCE_BUS " << SOURCE_BUS_depth << "}\n";
			total_list << "{source " << source_depth << "}\n";
			total_list << "{start " << start_depth << "}\n";
			total_list << "{ap_return " << ap_return_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int SOURCE_BUS_depth;
		int source_depth;
		int start_depth;
		int ap_return_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern int read_ocm (
int* source,
int start);

int AESL_WRAP_read_ocm (
int* source,
int start)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		int AESL_return;

		// output port post check: "SOURCE_BUS"
		aesl_fh.read(AUTOTB_TVOUT_PC_SOURCE_BUS, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_SOURCE_BUS, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_SOURCE_BUS, AESL_token); // data

			sc_bv<32> *SOURCE_BUS_pc_buffer = new sc_bv<32>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'SOURCE_BUS', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'SOURCE_BUS', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					SOURCE_BUS_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_SOURCE_BUS, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_SOURCE_BUS))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: SOURCE_BUS
				{
					// bitslice(31, 0)
					// {
						// celement: source(31, 0)
						// {
							sc_lv<32>* source_lv0_0_0_1 = new sc_lv<32>[1];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: source(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(source[0]) != NULL) // check the null address if the c port is array or others
								{
									source_lv0_0_0_1[hls_map_index++].range(31, 0) = sc_bv<32>(SOURCE_BUS_pc_buffer[hls_map_index].range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: source(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : source[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : source[0]
								// output_left_conversion : source[i_0]
								// output_type_conversion : (source_lv0_0_0_1[hls_map_index++]).to_uint64()
								if (&(source[0]) != NULL) // check the null address if the c port is array or others
								{
									source[i_0] = (source_lv0_0_0_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] SOURCE_BUS_pc_buffer;
		}

		// output port post check: "ap_return"
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data

			sc_bv<32> ap_return_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					ap_return_pc_buffer = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_ap_return))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: ap_return
				{
					// bitslice(31, 0)
					// {
						// celement: return(31, 0)
						// {
							sc_lv<32> return_lv0_0_1_0;
						// }
					// }

					// bitslice(31, 0)
					{
						// celement: return(31, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									return_lv0_0_1_0.range(31, 0) = sc_bv<32>(ap_return_pc_buffer.range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						// celement: return(31, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								// sub                    : 
								// ori_name               : AESL_return
								// sub_1st_elem           : 
								// ori_name_1st_elem      : AESL_return
								// output_left_conversion : AESL_return
								// output_type_conversion : (return_lv0_0_1_0).to_uint64()
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									AESL_return = (return_lv0_0_1_0).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		AESL_transaction_pc++;

		return AESL_return;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "SOURCE_BUS"
		char* tvin_SOURCE_BUS = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_SOURCE_BUS);
		char* tvout_SOURCE_BUS = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_SOURCE_BUS);

		// "source"
		char* tvin_source = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_source);

		// "start"
		char* tvin_start = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_start);

		// "ap_return"
		char* tvout_ap_return = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_ap_return);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_SOURCE_BUS, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_SOURCE_BUS, tvin_SOURCE_BUS);

		sc_bv<32>* SOURCE_BUS_tvin_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: SOURCE_BUS
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: source(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : source[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : source[0]
						// regulate_c_name       : source
						// input_type_conversion : source[i_0]
						if (&(source[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> source_tmp_mem;
							source_tmp_mem = source[i_0];
							SOURCE_BUS_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = source_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_SOURCE_BUS, "%s\n", (SOURCE_BUS_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_SOURCE_BUS, tvin_SOURCE_BUS);
		}

		tcl_file.set_num(1, &tcl_file.SOURCE_BUS_depth);
		sprintf(tvin_SOURCE_BUS, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_SOURCE_BUS, tvin_SOURCE_BUS);

		// release memory allocation
		delete [] SOURCE_BUS_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_source, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_source, tvin_source);

		sc_bv<32> source_tvin_wrapc_buffer;

		// RTL Name: source
		{
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_source, "%s\n", (source_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_source, tvin_source);
		}

		tcl_file.set_num(1, &tcl_file.source_depth);
		sprintf(tvin_source, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_source, tvin_source);

		// [[transaction]]
		sprintf(tvin_start, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_start, tvin_start);

		sc_bv<32> start_tvin_wrapc_buffer;

		// RTL Name: start
		{
			// bitslice(31, 0)
			{
				// celement: start(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : start
						// sub_1st_elem          : 
						// ori_name_1st_elem     : start
						// regulate_c_name       : start
						// input_type_conversion : start
						if (&(start) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> start_tmp_mem;
							start_tmp_mem = start;
							start_tvin_wrapc_buffer.range(31, 0) = start_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_start, "%s\n", (start_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_start, tvin_start);
		}

		tcl_file.set_num(1, &tcl_file.start_depth);
		sprintf(tvin_start, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_start, tvin_start);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		int AESL_return = read_ocm(source, start);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_SOURCE_BUS, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_SOURCE_BUS, tvout_SOURCE_BUS);

		sc_bv<32>* SOURCE_BUS_tvout_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: SOURCE_BUS
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: source(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : source[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : source[0]
						// regulate_c_name       : source
						// input_type_conversion : source[i_0]
						if (&(source[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> source_tmp_mem;
							source_tmp_mem = source[i_0];
							SOURCE_BUS_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = source_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_SOURCE_BUS, "%s\n", (SOURCE_BUS_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_SOURCE_BUS, tvout_SOURCE_BUS);
		}

		tcl_file.set_num(1, &tcl_file.SOURCE_BUS_depth);
		sprintf(tvout_SOURCE_BUS, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_SOURCE_BUS, tvout_SOURCE_BUS);

		// release memory allocation
		delete [] SOURCE_BUS_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_ap_return, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		sc_bv<32> ap_return_tvout_wrapc_buffer;

		// RTL Name: ap_return
		{
			// bitslice(31, 0)
			{
				// celement: return(31, 0)
				{
					// carray: (0) => (1) @ (0)
					{
						// sub                   : 
						// ori_name              : AESL_return
						// sub_1st_elem          : 
						// ori_name_1st_elem     : AESL_return
						// regulate_c_name       : return
						// input_type_conversion : AESL_return
						if (&(AESL_return) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> return_tmp_mem;
							return_tmp_mem = AESL_return;
							ap_return_tvout_wrapc_buffer.range(31, 0) = return_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_ap_return, "%s\n", (ap_return_tvout_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);
		}

		tcl_file.set_num(1, &tcl_file.ap_return_depth);
		sprintf(tvout_ap_return, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "SOURCE_BUS"
		delete [] tvin_SOURCE_BUS;
		delete [] tvout_SOURCE_BUS;
		// release memory allocation: "source"
		delete [] tvin_source;
		// release memory allocation: "start"
		delete [] tvin_start;
		// release memory allocation: "ap_return"
		delete [] tvout_ap_return;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

		return AESL_return;
	}
}

