// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSKIPPREFETCH_NELEM_H
#define XSKIPPREFETCH_NELEM_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xskipprefetch_nelem_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Cfg_BaseAddress;
} XSkipprefetch_nelem_Config;
#endif

typedef struct {
    u32 Cfg_BaseAddress;
    u32 IsReady;
} XSkipprefetch_nelem;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSkipprefetch_nelem_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSkipprefetch_nelem_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSkipprefetch_nelem_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSkipprefetch_nelem_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSkipprefetch_nelem_Initialize(XSkipprefetch_nelem *InstancePtr, u16 DeviceId);
XSkipprefetch_nelem_Config* XSkipprefetch_nelem_LookupConfig(u16 DeviceId);
int XSkipprefetch_nelem_CfgInitialize(XSkipprefetch_nelem *InstancePtr, XSkipprefetch_nelem_Config *ConfigPtr);
#else
int XSkipprefetch_nelem_Initialize(XSkipprefetch_nelem *InstancePtr, const char* InstanceName);
int XSkipprefetch_nelem_Release(XSkipprefetch_nelem *InstancePtr);
#endif

void XSkipprefetch_nelem_Start(XSkipprefetch_nelem *InstancePtr);
u32 XSkipprefetch_nelem_IsDone(XSkipprefetch_nelem *InstancePtr);
u32 XSkipprefetch_nelem_IsIdle(XSkipprefetch_nelem *InstancePtr);
u32 XSkipprefetch_nelem_IsReady(XSkipprefetch_nelem *InstancePtr);
void XSkipprefetch_nelem_EnableAutoRestart(XSkipprefetch_nelem *InstancePtr);
void XSkipprefetch_nelem_DisableAutoRestart(XSkipprefetch_nelem *InstancePtr);

void XSkipprefetch_nelem_Set_a(XSkipprefetch_nelem *InstancePtr, u32 Data);
u32 XSkipprefetch_nelem_Get_a(XSkipprefetch_nelem *InstancePtr);

void XSkipprefetch_nelem_InterruptGlobalEnable(XSkipprefetch_nelem *InstancePtr);
void XSkipprefetch_nelem_InterruptGlobalDisable(XSkipprefetch_nelem *InstancePtr);
void XSkipprefetch_nelem_InterruptEnable(XSkipprefetch_nelem *InstancePtr, u32 Mask);
void XSkipprefetch_nelem_InterruptDisable(XSkipprefetch_nelem *InstancePtr, u32 Mask);
void XSkipprefetch_nelem_InterruptClear(XSkipprefetch_nelem *InstancePtr, u32 Mask);
u32 XSkipprefetch_nelem_InterruptGetEnabled(XSkipprefetch_nelem *InstancePtr);
u32 XSkipprefetch_nelem_InterruptGetStatus(XSkipprefetch_nelem *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
