// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfetch_log.h"

extern XFetch_log_Config XFetch_log_ConfigTable[];

XFetch_log_Config *XFetch_log_LookupConfig(u16 DeviceId) {
	XFetch_log_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFETCH_LOG_NUM_INSTANCES; Index++) {
		if (XFetch_log_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFetch_log_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFetch_log_Initialize(XFetch_log *InstancePtr, u16 DeviceId) {
	XFetch_log_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFetch_log_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFetch_log_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

