// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xread_ocm.h"

extern XRead_ocm_Config XRead_ocm_ConfigTable[];

XRead_ocm_Config *XRead_ocm_LookupConfig(u16 DeviceId) {
	XRead_ocm_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XREAD_OCM_NUM_INSTANCES; Index++) {
		if (XRead_ocm_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XRead_ocm_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XRead_ocm_Initialize(XRead_ocm *InstancePtr, u16 DeviceId) {
	XRead_ocm_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XRead_ocm_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XRead_ocm_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

