// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XFETCH_RETVOID_H
#define XFETCH_RETVOID_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xfetch_retvoid_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Cfg_BaseAddress;
} XFetch_retvoid_Config;
#endif

typedef struct {
    u32 Cfg_BaseAddress;
    u32 IsReady;
} XFetch_retvoid;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XFetch_retvoid_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XFetch_retvoid_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XFetch_retvoid_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XFetch_retvoid_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XFetch_retvoid_Initialize(XFetch_retvoid *InstancePtr, u16 DeviceId);
XFetch_retvoid_Config* XFetch_retvoid_LookupConfig(u16 DeviceId);
int XFetch_retvoid_CfgInitialize(XFetch_retvoid *InstancePtr, XFetch_retvoid_Config *ConfigPtr);
#else
int XFetch_retvoid_Initialize(XFetch_retvoid *InstancePtr, const char* InstanceName);
int XFetch_retvoid_Release(XFetch_retvoid *InstancePtr);
#endif

void XFetch_retvoid_Start(XFetch_retvoid *InstancePtr);
u32 XFetch_retvoid_IsDone(XFetch_retvoid *InstancePtr);
u32 XFetch_retvoid_IsIdle(XFetch_retvoid *InstancePtr);
u32 XFetch_retvoid_IsReady(XFetch_retvoid *InstancePtr);
void XFetch_retvoid_EnableAutoRestart(XFetch_retvoid *InstancePtr);
void XFetch_retvoid_DisableAutoRestart(XFetch_retvoid *InstancePtr);

void XFetch_retvoid_Set_a(XFetch_retvoid *InstancePtr, u32 Data);
u32 XFetch_retvoid_Get_a(XFetch_retvoid *InstancePtr);

void XFetch_retvoid_InterruptGlobalEnable(XFetch_retvoid *InstancePtr);
void XFetch_retvoid_InterruptGlobalDisable(XFetch_retvoid *InstancePtr);
void XFetch_retvoid_InterruptEnable(XFetch_retvoid *InstancePtr, u32 Mask);
void XFetch_retvoid_InterruptDisable(XFetch_retvoid *InstancePtr, u32 Mask);
void XFetch_retvoid_InterruptClear(XFetch_retvoid *InstancePtr, u32 Mask);
u32 XFetch_retvoid_InterruptGetEnabled(XFetch_retvoid *InstancePtr);
u32 XFetch_retvoid_InterruptGetStatus(XFetch_retvoid *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
