// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xprefetch.h"

extern XPrefetch_Config XPrefetch_ConfigTable[];

XPrefetch_Config *XPrefetch_LookupConfig(u16 DeviceId) {
	XPrefetch_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPREFETCH_NUM_INSTANCES; Index++) {
		if (XPrefetch_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPrefetch_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPrefetch_Initialize(XPrefetch *InstancePtr, u16 DeviceId) {
	XPrefetch_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPrefetch_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPrefetch_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

