// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "prefetch.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic prefetch::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic prefetch::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<19> prefetch::ap_ST_fsm_state1 = "1";
const sc_lv<19> prefetch::ap_ST_fsm_state2 = "10";
const sc_lv<19> prefetch::ap_ST_fsm_state3 = "100";
const sc_lv<19> prefetch::ap_ST_fsm_state4 = "1000";
const sc_lv<19> prefetch::ap_ST_fsm_state5 = "10000";
const sc_lv<19> prefetch::ap_ST_fsm_state6 = "100000";
const sc_lv<19> prefetch::ap_ST_fsm_state7 = "1000000";
const sc_lv<19> prefetch::ap_ST_fsm_state8 = "10000000";
const sc_lv<19> prefetch::ap_ST_fsm_state9 = "100000000";
const sc_lv<19> prefetch::ap_ST_fsm_state10 = "1000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state11 = "10000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state12 = "100000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<19> prefetch::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<32> prefetch::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> prefetch::ap_const_lv1_1 = "1";
const sc_lv<32> prefetch::ap_const_lv32_1 = "1";
const sc_lv<32> prefetch::ap_const_lv32_8 = "1000";
const sc_lv<32> prefetch::ap_const_lv32_9 = "1001";
const sc_lv<32> prefetch::ap_const_lv32_A = "1010";
const sc_lv<32> prefetch::ap_const_lv32_B = "1011";
const sc_lv<32> prefetch::ap_const_lv32_C = "1100";
const sc_lv<32> prefetch::ap_const_lv32_D = "1101";
const sc_lv<32> prefetch::ap_const_lv32_E = "1110";
const sc_lv<32> prefetch::ap_const_lv32_F = "1111";
const sc_lv<32> prefetch::ap_const_lv32_10 = "10000";
const sc_lv<32> prefetch::ap_const_lv32_11 = "10001";
const int prefetch::C_S_AXI_DATA_WIDTH = "100000";
const int prefetch::C_M_AXI_DATA_WIDTH = "100000";
const int prefetch::C_M_AXI_SOURCE_BUS_USER_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int prefetch::C_M_AXI_SOURCE_BUS_PROT_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int prefetch::C_M_AXI_SOURCE_BUS_CACHE_VALUE = "11";
const sc_lv<1> prefetch::ap_const_lv1_0 = "0";
const sc_lv<3> prefetch::ap_const_lv3_0 = "000";
const sc_lv<2> prefetch::ap_const_lv2_0 = "00";
const sc_lv<4> prefetch::ap_const_lv4_0 = "0000";
const sc_lv<32> prefetch::ap_const_lv32_2 = "10";
const sc_lv<32> prefetch::ap_const_lv32_1F = "11111";
const sc_lv<2> prefetch::ap_const_lv2_2 = "10";
const sc_lv<2> prefetch::ap_const_lv2_1 = "1";
const sc_lv<32> prefetch::ap_const_lv32_3 = "11";
const sc_lv<3> prefetch::ap_const_lv3_1 = "1";
const sc_lv<32> prefetch::ap_const_lv32_4 = "100";
const sc_lv<32> prefetch::ap_const_lv32_5 = "101";
const sc_lv<32> prefetch::ap_const_lv32_6 = "110";
const sc_lv<32> prefetch::ap_const_lv32_7 = "111";
const sc_lv<4> prefetch::ap_const_lv4_1 = "1";
const sc_lv<32> prefetch::ap_const_lv32_12 = "10010";
const sc_lv<4> prefetch::ap_const_lv4_A = "1010";

prefetch::prefetch(sc_module_name name) : sc_module(name), mVcdFile(0) {
    prefetch_AXILiteS_s_axi_U = new prefetch_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("prefetch_AXILiteS_s_axi_U");
    prefetch_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    prefetch_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    prefetch_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    prefetch_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    prefetch_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    prefetch_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    prefetch_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    prefetch_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    prefetch_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    prefetch_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    prefetch_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    prefetch_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    prefetch_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    prefetch_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    prefetch_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    prefetch_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    prefetch_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    prefetch_AXILiteS_s_axi_U->ACLK(ap_clk);
    prefetch_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    prefetch_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    prefetch_AXILiteS_s_axi_U->ap_start(ap_start);
    prefetch_AXILiteS_s_axi_U->interrupt(interrupt);
    prefetch_AXILiteS_s_axi_U->ap_ready(ap_ready);
    prefetch_AXILiteS_s_axi_U->ap_done(ap_done);
    prefetch_AXILiteS_s_axi_U->ap_idle(ap_idle);
    prefetch_AXILiteS_s_axi_U->ap_return(ap_return);
    prefetch_AXILiteS_s_axi_U->source(source);
    prefetch_SOURCE_BUS_m_axi_U = new prefetch_SOURCE_BUS_m_axi<32,32,5,16,16,16,16,C_M_AXI_SOURCE_BUS_ID_WIDTH,C_M_AXI_SOURCE_BUS_ADDR_WIDTH,C_M_AXI_SOURCE_BUS_DATA_WIDTH,C_M_AXI_SOURCE_BUS_AWUSER_WIDTH,C_M_AXI_SOURCE_BUS_ARUSER_WIDTH,C_M_AXI_SOURCE_BUS_WUSER_WIDTH,C_M_AXI_SOURCE_BUS_RUSER_WIDTH,C_M_AXI_SOURCE_BUS_BUSER_WIDTH,C_M_AXI_SOURCE_BUS_USER_VALUE,C_M_AXI_SOURCE_BUS_PROT_VALUE,C_M_AXI_SOURCE_BUS_CACHE_VALUE>("prefetch_SOURCE_BUS_m_axi_U");
    prefetch_SOURCE_BUS_m_axi_U->AWVALID(m_axi_SOURCE_BUS_AWVALID);
    prefetch_SOURCE_BUS_m_axi_U->AWREADY(m_axi_SOURCE_BUS_AWREADY);
    prefetch_SOURCE_BUS_m_axi_U->AWADDR(m_axi_SOURCE_BUS_AWADDR);
    prefetch_SOURCE_BUS_m_axi_U->AWID(m_axi_SOURCE_BUS_AWID);
    prefetch_SOURCE_BUS_m_axi_U->AWLEN(m_axi_SOURCE_BUS_AWLEN);
    prefetch_SOURCE_BUS_m_axi_U->AWSIZE(m_axi_SOURCE_BUS_AWSIZE);
    prefetch_SOURCE_BUS_m_axi_U->AWBURST(m_axi_SOURCE_BUS_AWBURST);
    prefetch_SOURCE_BUS_m_axi_U->AWLOCK(m_axi_SOURCE_BUS_AWLOCK);
    prefetch_SOURCE_BUS_m_axi_U->AWCACHE(m_axi_SOURCE_BUS_AWCACHE);
    prefetch_SOURCE_BUS_m_axi_U->AWPROT(m_axi_SOURCE_BUS_AWPROT);
    prefetch_SOURCE_BUS_m_axi_U->AWQOS(m_axi_SOURCE_BUS_AWQOS);
    prefetch_SOURCE_BUS_m_axi_U->AWREGION(m_axi_SOURCE_BUS_AWREGION);
    prefetch_SOURCE_BUS_m_axi_U->AWUSER(m_axi_SOURCE_BUS_AWUSER);
    prefetch_SOURCE_BUS_m_axi_U->WVALID(m_axi_SOURCE_BUS_WVALID);
    prefetch_SOURCE_BUS_m_axi_U->WREADY(m_axi_SOURCE_BUS_WREADY);
    prefetch_SOURCE_BUS_m_axi_U->WDATA(m_axi_SOURCE_BUS_WDATA);
    prefetch_SOURCE_BUS_m_axi_U->WSTRB(m_axi_SOURCE_BUS_WSTRB);
    prefetch_SOURCE_BUS_m_axi_U->WLAST(m_axi_SOURCE_BUS_WLAST);
    prefetch_SOURCE_BUS_m_axi_U->WID(m_axi_SOURCE_BUS_WID);
    prefetch_SOURCE_BUS_m_axi_U->WUSER(m_axi_SOURCE_BUS_WUSER);
    prefetch_SOURCE_BUS_m_axi_U->ARVALID(m_axi_SOURCE_BUS_ARVALID);
    prefetch_SOURCE_BUS_m_axi_U->ARREADY(m_axi_SOURCE_BUS_ARREADY);
    prefetch_SOURCE_BUS_m_axi_U->ARADDR(m_axi_SOURCE_BUS_ARADDR);
    prefetch_SOURCE_BUS_m_axi_U->ARID(m_axi_SOURCE_BUS_ARID);
    prefetch_SOURCE_BUS_m_axi_U->ARLEN(m_axi_SOURCE_BUS_ARLEN);
    prefetch_SOURCE_BUS_m_axi_U->ARSIZE(m_axi_SOURCE_BUS_ARSIZE);
    prefetch_SOURCE_BUS_m_axi_U->ARBURST(m_axi_SOURCE_BUS_ARBURST);
    prefetch_SOURCE_BUS_m_axi_U->ARLOCK(m_axi_SOURCE_BUS_ARLOCK);
    prefetch_SOURCE_BUS_m_axi_U->ARCACHE(m_axi_SOURCE_BUS_ARCACHE);
    prefetch_SOURCE_BUS_m_axi_U->ARPROT(m_axi_SOURCE_BUS_ARPROT);
    prefetch_SOURCE_BUS_m_axi_U->ARQOS(m_axi_SOURCE_BUS_ARQOS);
    prefetch_SOURCE_BUS_m_axi_U->ARREGION(m_axi_SOURCE_BUS_ARREGION);
    prefetch_SOURCE_BUS_m_axi_U->ARUSER(m_axi_SOURCE_BUS_ARUSER);
    prefetch_SOURCE_BUS_m_axi_U->RVALID(m_axi_SOURCE_BUS_RVALID);
    prefetch_SOURCE_BUS_m_axi_U->RREADY(m_axi_SOURCE_BUS_RREADY);
    prefetch_SOURCE_BUS_m_axi_U->RDATA(m_axi_SOURCE_BUS_RDATA);
    prefetch_SOURCE_BUS_m_axi_U->RLAST(m_axi_SOURCE_BUS_RLAST);
    prefetch_SOURCE_BUS_m_axi_U->RID(m_axi_SOURCE_BUS_RID);
    prefetch_SOURCE_BUS_m_axi_U->RUSER(m_axi_SOURCE_BUS_RUSER);
    prefetch_SOURCE_BUS_m_axi_U->RRESP(m_axi_SOURCE_BUS_RRESP);
    prefetch_SOURCE_BUS_m_axi_U->BVALID(m_axi_SOURCE_BUS_BVALID);
    prefetch_SOURCE_BUS_m_axi_U->BREADY(m_axi_SOURCE_BUS_BREADY);
    prefetch_SOURCE_BUS_m_axi_U->BRESP(m_axi_SOURCE_BUS_BRESP);
    prefetch_SOURCE_BUS_m_axi_U->BID(m_axi_SOURCE_BUS_BID);
    prefetch_SOURCE_BUS_m_axi_U->BUSER(m_axi_SOURCE_BUS_BUSER);
    prefetch_SOURCE_BUS_m_axi_U->ACLK(ap_clk);
    prefetch_SOURCE_BUS_m_axi_U->ARESET(ap_rst_n_inv);
    prefetch_SOURCE_BUS_m_axi_U->ACLK_EN(ap_var_for_const0);
    prefetch_SOURCE_BUS_m_axi_U->I_ARVALID(SOURCE_BUS_ARVALID);
    prefetch_SOURCE_BUS_m_axi_U->I_ARREADY(SOURCE_BUS_ARREADY);
    prefetch_SOURCE_BUS_m_axi_U->I_ARADDR(tmp_2_fu_102_p1);
    prefetch_SOURCE_BUS_m_axi_U->I_ARID(ap_var_for_const1);
    prefetch_SOURCE_BUS_m_axi_U->I_ARLEN(ap_var_for_const2);
    prefetch_SOURCE_BUS_m_axi_U->I_ARSIZE(ap_var_for_const3);
    prefetch_SOURCE_BUS_m_axi_U->I_ARLOCK(ap_var_for_const4);
    prefetch_SOURCE_BUS_m_axi_U->I_ARCACHE(ap_var_for_const5);
    prefetch_SOURCE_BUS_m_axi_U->I_ARQOS(ap_var_for_const5);
    prefetch_SOURCE_BUS_m_axi_U->I_ARPROT(ap_var_for_const3);
    prefetch_SOURCE_BUS_m_axi_U->I_ARUSER(ap_var_for_const1);
    prefetch_SOURCE_BUS_m_axi_U->I_ARBURST(ap_var_for_const4);
    prefetch_SOURCE_BUS_m_axi_U->I_ARREGION(ap_var_for_const5);
    prefetch_SOURCE_BUS_m_axi_U->I_RVALID(SOURCE_BUS_RVALID);
    prefetch_SOURCE_BUS_m_axi_U->I_RREADY(SOURCE_BUS_RREADY);
    prefetch_SOURCE_BUS_m_axi_U->I_RDATA(SOURCE_BUS_RDATA);
    prefetch_SOURCE_BUS_m_axi_U->I_RID(SOURCE_BUS_RID);
    prefetch_SOURCE_BUS_m_axi_U->I_RUSER(SOURCE_BUS_RUSER);
    prefetch_SOURCE_BUS_m_axi_U->I_RRESP(SOURCE_BUS_RRESP);
    prefetch_SOURCE_BUS_m_axi_U->I_RLAST(SOURCE_BUS_RLAST);
    prefetch_SOURCE_BUS_m_axi_U->I_AWVALID(ap_var_for_const6);
    prefetch_SOURCE_BUS_m_axi_U->I_AWREADY(SOURCE_BUS_AWREADY);
    prefetch_SOURCE_BUS_m_axi_U->I_AWADDR(ap_var_for_const7);
    prefetch_SOURCE_BUS_m_axi_U->I_AWID(ap_var_for_const1);
    prefetch_SOURCE_BUS_m_axi_U->I_AWLEN(ap_var_for_const7);
    prefetch_SOURCE_BUS_m_axi_U->I_AWSIZE(ap_var_for_const3);
    prefetch_SOURCE_BUS_m_axi_U->I_AWLOCK(ap_var_for_const4);
    prefetch_SOURCE_BUS_m_axi_U->I_AWCACHE(ap_var_for_const5);
    prefetch_SOURCE_BUS_m_axi_U->I_AWQOS(ap_var_for_const5);
    prefetch_SOURCE_BUS_m_axi_U->I_AWPROT(ap_var_for_const3);
    prefetch_SOURCE_BUS_m_axi_U->I_AWUSER(ap_var_for_const1);
    prefetch_SOURCE_BUS_m_axi_U->I_AWBURST(ap_var_for_const4);
    prefetch_SOURCE_BUS_m_axi_U->I_AWREGION(ap_var_for_const5);
    prefetch_SOURCE_BUS_m_axi_U->I_WVALID(ap_var_for_const6);
    prefetch_SOURCE_BUS_m_axi_U->I_WREADY(SOURCE_BUS_WREADY);
    prefetch_SOURCE_BUS_m_axi_U->I_WDATA(ap_var_for_const7);
    prefetch_SOURCE_BUS_m_axi_U->I_WID(ap_var_for_const1);
    prefetch_SOURCE_BUS_m_axi_U->I_WUSER(ap_var_for_const1);
    prefetch_SOURCE_BUS_m_axi_U->I_WLAST(ap_var_for_const6);
    prefetch_SOURCE_BUS_m_axi_U->I_WSTRB(ap_var_for_const5);
    prefetch_SOURCE_BUS_m_axi_U->I_BVALID(SOURCE_BUS_BVALID);
    prefetch_SOURCE_BUS_m_axi_U->I_BREADY(ap_var_for_const6);
    prefetch_SOURCE_BUS_m_axi_U->I_BRESP(SOURCE_BUS_BRESP);
    prefetch_SOURCE_BUS_m_axi_U->I_BID(SOURCE_BUS_BID);
    prefetch_SOURCE_BUS_m_axi_U->I_BUSER(SOURCE_BUS_BUSER);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_SOURCE_BUS_ARVALID);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_reg_ioackin_SOURCE_BUS_ARREADY );

    SC_METHOD(thread_SOURCE_BUS_RREADY);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( SOURCE_BUS_RVALID );

    SC_METHOD(thread_SOURCE_BUS_blk_n_AR);
    sensitive << ( m_axi_SOURCE_BUS_ARREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_SOURCE_BUS_blk_n_R);
    sensitive << ( m_axi_SOURCE_BUS_RVALID );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_fu_299_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_ioackin_SOURCE_BUS_ARREADY);
    sensitive << ( SOURCE_BUS_ARREADY );
    sensitive << ( ap_reg_ioackin_SOURCE_BUS_ARREADY );

    SC_METHOD(thread_c_flag_1_1_fu_127_p3);
    sensitive << ( tmp_1_reg_320 );

    SC_METHOD(thread_c_flag_1_2_fu_147_p2);
    sensitive << ( p_c_flag_1_fu_134_p3 );

    SC_METHOD(thread_c_flag_1_3_fu_170_p2);
    sensitive << ( p_c_flag_2_cast_fu_167_p1 );

    SC_METHOD(thread_c_flag_1_4_fu_189_p2);
    sensitive << ( p_c_flag_3_fu_176_p3 );

    SC_METHOD(thread_c_flag_1_5_fu_209_p2);
    sensitive << ( p_c_flag_4_reg_341 );

    SC_METHOD(thread_c_flag_1_6_fu_227_p2);
    sensitive << ( p_c_flag_5_reg_347 );

    SC_METHOD(thread_c_flag_1_7_fu_248_p2);
    sensitive << ( p_c_flag_6_cast_fu_245_p1 );

    SC_METHOD(thread_c_flag_1_8_fu_267_p2);
    sensitive << ( p_c_flag_7_fu_254_p3 );

    SC_METHOD(thread_c_flag_1_9_fu_287_p2);
    sensitive << ( p_c_flag_8_reg_363 );

    SC_METHOD(thread_p_c_flag_1_fu_134_p3);
    sensitive << ( tmp_1_1_reg_326 );
    sensitive << ( c_flag_1_1_fu_127_p3 );
    sensitive << ( p_c_flag_cast_fu_124_p1 );

    SC_METHOD(thread_p_c_flag_2_cast_fu_167_p1);
    sensitive << ( p_c_flag_2_reg_331 );

    SC_METHOD(thread_p_c_flag_2_fu_153_p3);
    sensitive << ( p_c_flag_1_fu_134_p3 );
    sensitive << ( tmp_1_2_fu_141_p2 );
    sensitive << ( c_flag_1_2_fu_147_p2 );

    SC_METHOD(thread_p_c_flag_3_fu_176_p3);
    sensitive << ( tmp_1_3_reg_336 );
    sensitive << ( p_c_flag_2_cast_fu_167_p1 );
    sensitive << ( c_flag_1_3_fu_170_p2 );

    SC_METHOD(thread_p_c_flag_4_fu_195_p3);
    sensitive << ( p_c_flag_3_fu_176_p3 );
    sensitive << ( tmp_1_4_fu_183_p2 );
    sensitive << ( c_flag_1_4_fu_189_p2 );

    SC_METHOD(thread_p_c_flag_5_fu_214_p3);
    sensitive << ( p_c_flag_4_reg_341 );
    sensitive << ( tmp_1_5_fu_203_p2 );
    sensitive << ( c_flag_1_5_fu_209_p2 );

    SC_METHOD(thread_p_c_flag_6_cast_fu_245_p1);
    sensitive << ( p_c_flag_6_reg_353 );

    SC_METHOD(thread_p_c_flag_6_fu_232_p3);
    sensitive << ( p_c_flag_5_reg_347 );
    sensitive << ( tmp_1_6_fu_221_p2 );
    sensitive << ( c_flag_1_6_fu_227_p2 );

    SC_METHOD(thread_p_c_flag_7_fu_254_p3);
    sensitive << ( tmp_1_7_reg_358 );
    sensitive << ( p_c_flag_6_cast_fu_245_p1 );
    sensitive << ( c_flag_1_7_fu_248_p2 );

    SC_METHOD(thread_p_c_flag_8_fu_273_p3);
    sensitive << ( p_c_flag_7_fu_254_p3 );
    sensitive << ( tmp_1_8_fu_261_p2 );
    sensitive << ( c_flag_1_8_fu_267_p2 );

    SC_METHOD(thread_p_c_flag_9_fu_292_p3);
    sensitive << ( p_c_flag_8_reg_363 );
    sensitive << ( tmp_1_9_fu_281_p2 );
    sensitive << ( c_flag_1_9_fu_287_p2 );

    SC_METHOD(thread_p_c_flag_cast_fu_124_p1);
    sensitive << ( tmp_1_reg_320 );

    SC_METHOD(thread_tmp_1_1_fu_118_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_1_2_fu_141_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_1_3_fu_161_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_1_4_fu_183_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_1_5_fu_203_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_1_6_fu_221_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_1_7_fu_239_p2);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_1_8_fu_261_p2);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_1_9_fu_281_p2);
    sensitive << ( reg_88 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_tmp_1_fu_112_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( reg_88 );

    SC_METHOD(thread_tmp_2_fu_102_p1);
    sensitive << ( source1_reg_309 );

    SC_METHOD(thread_tmp_fu_299_p2);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( p_c_flag_9_fu_292_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( SOURCE_BUS_RVALID );
    sensitive << ( ap_sig_ioackin_SOURCE_BUS_ARREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const7);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const5);

    ap_CS_fsm = "0000000000000000001";
    ap_reg_ioackin_SOURCE_BUS_ARREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "prefetch_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWVALID, "(port)m_axi_SOURCE_BUS_AWVALID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWREADY, "(port)m_axi_SOURCE_BUS_AWREADY");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWADDR, "(port)m_axi_SOURCE_BUS_AWADDR");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWID, "(port)m_axi_SOURCE_BUS_AWID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWLEN, "(port)m_axi_SOURCE_BUS_AWLEN");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWSIZE, "(port)m_axi_SOURCE_BUS_AWSIZE");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWBURST, "(port)m_axi_SOURCE_BUS_AWBURST");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWLOCK, "(port)m_axi_SOURCE_BUS_AWLOCK");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWCACHE, "(port)m_axi_SOURCE_BUS_AWCACHE");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWPROT, "(port)m_axi_SOURCE_BUS_AWPROT");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWQOS, "(port)m_axi_SOURCE_BUS_AWQOS");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWREGION, "(port)m_axi_SOURCE_BUS_AWREGION");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_AWUSER, "(port)m_axi_SOURCE_BUS_AWUSER");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_WVALID, "(port)m_axi_SOURCE_BUS_WVALID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_WREADY, "(port)m_axi_SOURCE_BUS_WREADY");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_WDATA, "(port)m_axi_SOURCE_BUS_WDATA");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_WSTRB, "(port)m_axi_SOURCE_BUS_WSTRB");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_WLAST, "(port)m_axi_SOURCE_BUS_WLAST");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_WID, "(port)m_axi_SOURCE_BUS_WID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_WUSER, "(port)m_axi_SOURCE_BUS_WUSER");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARVALID, "(port)m_axi_SOURCE_BUS_ARVALID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARREADY, "(port)m_axi_SOURCE_BUS_ARREADY");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARADDR, "(port)m_axi_SOURCE_BUS_ARADDR");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARID, "(port)m_axi_SOURCE_BUS_ARID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARLEN, "(port)m_axi_SOURCE_BUS_ARLEN");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARSIZE, "(port)m_axi_SOURCE_BUS_ARSIZE");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARBURST, "(port)m_axi_SOURCE_BUS_ARBURST");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARLOCK, "(port)m_axi_SOURCE_BUS_ARLOCK");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARCACHE, "(port)m_axi_SOURCE_BUS_ARCACHE");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARPROT, "(port)m_axi_SOURCE_BUS_ARPROT");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARQOS, "(port)m_axi_SOURCE_BUS_ARQOS");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARREGION, "(port)m_axi_SOURCE_BUS_ARREGION");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_ARUSER, "(port)m_axi_SOURCE_BUS_ARUSER");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_RVALID, "(port)m_axi_SOURCE_BUS_RVALID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_RREADY, "(port)m_axi_SOURCE_BUS_RREADY");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_RDATA, "(port)m_axi_SOURCE_BUS_RDATA");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_RLAST, "(port)m_axi_SOURCE_BUS_RLAST");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_RID, "(port)m_axi_SOURCE_BUS_RID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_RUSER, "(port)m_axi_SOURCE_BUS_RUSER");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_RRESP, "(port)m_axi_SOURCE_BUS_RRESP");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_BVALID, "(port)m_axi_SOURCE_BUS_BVALID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_BREADY, "(port)m_axi_SOURCE_BUS_BREADY");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_BRESP, "(port)m_axi_SOURCE_BUS_BRESP");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_BID, "(port)m_axi_SOURCE_BUS_BID");
    sc_trace(mVcdFile, m_axi_SOURCE_BUS_BUSER, "(port)m_axi_SOURCE_BUS_BUSER");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, source, "source");
    sc_trace(mVcdFile, ap_return, "ap_return");
    sc_trace(mVcdFile, SOURCE_BUS_blk_n_AR, "SOURCE_BUS_blk_n_AR");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, SOURCE_BUS_blk_n_R, "SOURCE_BUS_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, SOURCE_BUS_AWREADY, "SOURCE_BUS_AWREADY");
    sc_trace(mVcdFile, SOURCE_BUS_WREADY, "SOURCE_BUS_WREADY");
    sc_trace(mVcdFile, SOURCE_BUS_ARVALID, "SOURCE_BUS_ARVALID");
    sc_trace(mVcdFile, SOURCE_BUS_ARREADY, "SOURCE_BUS_ARREADY");
    sc_trace(mVcdFile, SOURCE_BUS_RVALID, "SOURCE_BUS_RVALID");
    sc_trace(mVcdFile, SOURCE_BUS_RREADY, "SOURCE_BUS_RREADY");
    sc_trace(mVcdFile, SOURCE_BUS_RDATA, "SOURCE_BUS_RDATA");
    sc_trace(mVcdFile, SOURCE_BUS_RLAST, "SOURCE_BUS_RLAST");
    sc_trace(mVcdFile, SOURCE_BUS_RID, "SOURCE_BUS_RID");
    sc_trace(mVcdFile, SOURCE_BUS_RUSER, "SOURCE_BUS_RUSER");
    sc_trace(mVcdFile, SOURCE_BUS_RRESP, "SOURCE_BUS_RRESP");
    sc_trace(mVcdFile, SOURCE_BUS_BVALID, "SOURCE_BUS_BVALID");
    sc_trace(mVcdFile, SOURCE_BUS_BRESP, "SOURCE_BUS_BRESP");
    sc_trace(mVcdFile, SOURCE_BUS_BID, "SOURCE_BUS_BID");
    sc_trace(mVcdFile, SOURCE_BUS_BUSER, "SOURCE_BUS_BUSER");
    sc_trace(mVcdFile, reg_88, "reg_88");
    sc_trace(mVcdFile, source1_reg_309, "source1_reg_309");
    sc_trace(mVcdFile, ap_sig_ioackin_SOURCE_BUS_ARREADY, "ap_sig_ioackin_SOURCE_BUS_ARREADY");
    sc_trace(mVcdFile, tmp_1_fu_112_p2, "tmp_1_fu_112_p2");
    sc_trace(mVcdFile, tmp_1_reg_320, "tmp_1_reg_320");
    sc_trace(mVcdFile, tmp_1_1_fu_118_p2, "tmp_1_1_fu_118_p2");
    sc_trace(mVcdFile, tmp_1_1_reg_326, "tmp_1_1_reg_326");
    sc_trace(mVcdFile, p_c_flag_2_fu_153_p3, "p_c_flag_2_fu_153_p3");
    sc_trace(mVcdFile, p_c_flag_2_reg_331, "p_c_flag_2_reg_331");
    sc_trace(mVcdFile, tmp_1_3_fu_161_p2, "tmp_1_3_fu_161_p2");
    sc_trace(mVcdFile, tmp_1_3_reg_336, "tmp_1_3_reg_336");
    sc_trace(mVcdFile, p_c_flag_4_fu_195_p3, "p_c_flag_4_fu_195_p3");
    sc_trace(mVcdFile, p_c_flag_4_reg_341, "p_c_flag_4_reg_341");
    sc_trace(mVcdFile, p_c_flag_5_fu_214_p3, "p_c_flag_5_fu_214_p3");
    sc_trace(mVcdFile, p_c_flag_5_reg_347, "p_c_flag_5_reg_347");
    sc_trace(mVcdFile, p_c_flag_6_fu_232_p3, "p_c_flag_6_fu_232_p3");
    sc_trace(mVcdFile, p_c_flag_6_reg_353, "p_c_flag_6_reg_353");
    sc_trace(mVcdFile, tmp_1_7_fu_239_p2, "tmp_1_7_fu_239_p2");
    sc_trace(mVcdFile, tmp_1_7_reg_358, "tmp_1_7_reg_358");
    sc_trace(mVcdFile, p_c_flag_8_fu_273_p3, "p_c_flag_8_fu_273_p3");
    sc_trace(mVcdFile, p_c_flag_8_reg_363, "p_c_flag_8_reg_363");
    sc_trace(mVcdFile, tmp_2_fu_102_p1, "tmp_2_fu_102_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_SOURCE_BUS_ARREADY, "ap_reg_ioackin_SOURCE_BUS_ARREADY");
    sc_trace(mVcdFile, c_flag_1_1_fu_127_p3, "c_flag_1_1_fu_127_p3");
    sc_trace(mVcdFile, p_c_flag_cast_fu_124_p1, "p_c_flag_cast_fu_124_p1");
    sc_trace(mVcdFile, p_c_flag_1_fu_134_p3, "p_c_flag_1_fu_134_p3");
    sc_trace(mVcdFile, tmp_1_2_fu_141_p2, "tmp_1_2_fu_141_p2");
    sc_trace(mVcdFile, c_flag_1_2_fu_147_p2, "c_flag_1_2_fu_147_p2");
    sc_trace(mVcdFile, p_c_flag_2_cast_fu_167_p1, "p_c_flag_2_cast_fu_167_p1");
    sc_trace(mVcdFile, c_flag_1_3_fu_170_p2, "c_flag_1_3_fu_170_p2");
    sc_trace(mVcdFile, p_c_flag_3_fu_176_p3, "p_c_flag_3_fu_176_p3");
    sc_trace(mVcdFile, tmp_1_4_fu_183_p2, "tmp_1_4_fu_183_p2");
    sc_trace(mVcdFile, c_flag_1_4_fu_189_p2, "c_flag_1_4_fu_189_p2");
    sc_trace(mVcdFile, tmp_1_5_fu_203_p2, "tmp_1_5_fu_203_p2");
    sc_trace(mVcdFile, c_flag_1_5_fu_209_p2, "c_flag_1_5_fu_209_p2");
    sc_trace(mVcdFile, tmp_1_6_fu_221_p2, "tmp_1_6_fu_221_p2");
    sc_trace(mVcdFile, c_flag_1_6_fu_227_p2, "c_flag_1_6_fu_227_p2");
    sc_trace(mVcdFile, p_c_flag_6_cast_fu_245_p1, "p_c_flag_6_cast_fu_245_p1");
    sc_trace(mVcdFile, c_flag_1_7_fu_248_p2, "c_flag_1_7_fu_248_p2");
    sc_trace(mVcdFile, p_c_flag_7_fu_254_p3, "p_c_flag_7_fu_254_p3");
    sc_trace(mVcdFile, tmp_1_8_fu_261_p2, "tmp_1_8_fu_261_p2");
    sc_trace(mVcdFile, c_flag_1_8_fu_267_p2, "c_flag_1_8_fu_267_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, tmp_1_9_fu_281_p2, "tmp_1_9_fu_281_p2");
    sc_trace(mVcdFile, c_flag_1_9_fu_287_p2, "c_flag_1_9_fu_287_p2");
    sc_trace(mVcdFile, p_c_flag_9_fu_292_p3, "p_c_flag_9_fu_292_p3");
    sc_trace(mVcdFile, tmp_fu_299_p2, "tmp_fu_299_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("prefetch.hdltvin.dat");
    mHdltvoutHandle.open("prefetch.hdltvout.dat");
}

prefetch::~prefetch() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete prefetch_AXILiteS_s_axi_U;
    delete prefetch_SOURCE_BUS_m_axi_U;
}

void prefetch::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void prefetch::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_logic_0;
}

void prefetch::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv32_0;
}

void prefetch::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_A;
}

void prefetch::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void prefetch::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv3_0;
}

void prefetch::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv2_0;
}

void prefetch::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv4_0;
}

void prefetch::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_SOURCE_BUS_ARREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read())) {
            if (!esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_SOURCE_BUS_ARREADY.read())) {
                ap_reg_ioackin_SOURCE_BUS_ARREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, SOURCE_BUS_ARREADY.read())) {
                ap_reg_ioackin_SOURCE_BUS_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        p_c_flag_2_reg_331 = p_c_flag_2_fu_153_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        p_c_flag_4_reg_341 = p_c_flag_4_fu_195_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        p_c_flag_5_reg_347 = p_c_flag_5_fu_214_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        p_c_flag_6_reg_353 = p_c_flag_6_fu_232_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        p_c_flag_8_reg_363 = p_c_flag_8_fu_273_p3.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()) && 
  !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)))) {
        reg_88 = SOURCE_BUS_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        source1_reg_309 = source.read().range(31, 2);
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        tmp_1_1_reg_326 = tmp_1_1_fu_118_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        tmp_1_3_reg_336 = tmp_1_3_fu_161_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        tmp_1_7_reg_358 = tmp_1_7_fu_239_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()) && !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0))) {
        tmp_1_reg_320 = tmp_1_fu_112_p2.read();
    }
}

void prefetch::thread_SOURCE_BUS_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_SOURCE_BUS_ARREADY.read()))) {
        SOURCE_BUS_ARVALID = ap_const_logic_1;
    } else {
        SOURCE_BUS_ARVALID = ap_const_logic_0;
    }
}

void prefetch::thread_SOURCE_BUS_RREADY() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()) && 
          !esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)))) {
        SOURCE_BUS_RREADY = ap_const_logic_1;
    } else {
        SOURCE_BUS_RREADY = ap_const_logic_0;
    }
}

void prefetch::thread_SOURCE_BUS_blk_n_AR() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        SOURCE_BUS_blk_n_AR = m_axi_SOURCE_BUS_ARREADY.read();
    } else {
        SOURCE_BUS_blk_n_AR = ap_const_logic_1;
    }
}

void prefetch::thread_SOURCE_BUS_blk_n_R() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read())))) {
        SOURCE_BUS_blk_n_R = m_axi_SOURCE_BUS_RVALID.read();
    } else {
        SOURCE_BUS_blk_n_R = ap_const_logic_1;
    }
}

void prefetch::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void prefetch::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read().range(9, 9);
}

void prefetch::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read().range(10, 10);
}

void prefetch::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read().range(11, 11);
}

void prefetch::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read().range(12, 12);
}

void prefetch::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read().range(13, 13);
}

void prefetch::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read().range(14, 14);
}

void prefetch::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read().range(15, 15);
}

void prefetch::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read().range(16, 16);
}

void prefetch::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read().range(17, 17);
}

void prefetch::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read().range(18, 18);
}

void prefetch::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void prefetch::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read().range(8, 8);
}

void prefetch::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void prefetch::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void prefetch::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void prefetch::thread_ap_return() {
    ap_return = esl_zext<32,1>(tmp_fu_299_p2.read());
}

void prefetch::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void prefetch::thread_ap_sig_ioackin_SOURCE_BUS_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_SOURCE_BUS_ARREADY.read())) {
        ap_sig_ioackin_SOURCE_BUS_ARREADY = SOURCE_BUS_ARREADY.read();
    } else {
        ap_sig_ioackin_SOURCE_BUS_ARREADY = ap_const_logic_1;
    }
}

void prefetch::thread_c_flag_1_1_fu_127_p3() {
    c_flag_1_1_fu_127_p3 = (!tmp_1_reg_320.read()[0].is_01())? sc_lv<2>(): ((tmp_1_reg_320.read()[0].to_bool())? ap_const_lv2_2: ap_const_lv2_1);
}

void prefetch::thread_c_flag_1_2_fu_147_p2() {
    c_flag_1_2_fu_147_p2 = (!p_c_flag_1_fu_134_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(p_c_flag_1_fu_134_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void prefetch::thread_c_flag_1_3_fu_170_p2() {
    c_flag_1_3_fu_170_p2 = (!p_c_flag_2_cast_fu_167_p1.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_c_flag_2_cast_fu_167_p1.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void prefetch::thread_c_flag_1_4_fu_189_p2() {
    c_flag_1_4_fu_189_p2 = (!p_c_flag_3_fu_176_p3.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_c_flag_3_fu_176_p3.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void prefetch::thread_c_flag_1_5_fu_209_p2() {
    c_flag_1_5_fu_209_p2 = (!p_c_flag_4_reg_341.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_c_flag_4_reg_341.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void prefetch::thread_c_flag_1_6_fu_227_p2() {
    c_flag_1_6_fu_227_p2 = (!p_c_flag_5_reg_347.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_c_flag_5_reg_347.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void prefetch::thread_c_flag_1_7_fu_248_p2() {
    c_flag_1_7_fu_248_p2 = (!p_c_flag_6_cast_fu_245_p1.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(p_c_flag_6_cast_fu_245_p1.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void prefetch::thread_c_flag_1_8_fu_267_p2() {
    c_flag_1_8_fu_267_p2 = (!p_c_flag_7_fu_254_p3.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(p_c_flag_7_fu_254_p3.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void prefetch::thread_c_flag_1_9_fu_287_p2() {
    c_flag_1_9_fu_287_p2 = (!p_c_flag_8_reg_363.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(p_c_flag_8_reg_363.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void prefetch::thread_p_c_flag_1_fu_134_p3() {
    p_c_flag_1_fu_134_p3 = (!tmp_1_1_reg_326.read()[0].is_01())? sc_lv<2>(): ((tmp_1_1_reg_326.read()[0].to_bool())? c_flag_1_1_fu_127_p3.read(): p_c_flag_cast_fu_124_p1.read());
}

void prefetch::thread_p_c_flag_2_cast_fu_167_p1() {
    p_c_flag_2_cast_fu_167_p1 = esl_zext<3,2>(p_c_flag_2_reg_331.read());
}

void prefetch::thread_p_c_flag_2_fu_153_p3() {
    p_c_flag_2_fu_153_p3 = (!tmp_1_2_fu_141_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_1_2_fu_141_p2.read()[0].to_bool())? c_flag_1_2_fu_147_p2.read(): p_c_flag_1_fu_134_p3.read());
}

void prefetch::thread_p_c_flag_3_fu_176_p3() {
    p_c_flag_3_fu_176_p3 = (!tmp_1_3_reg_336.read()[0].is_01())? sc_lv<3>(): ((tmp_1_3_reg_336.read()[0].to_bool())? c_flag_1_3_fu_170_p2.read(): p_c_flag_2_cast_fu_167_p1.read());
}

void prefetch::thread_p_c_flag_4_fu_195_p3() {
    p_c_flag_4_fu_195_p3 = (!tmp_1_4_fu_183_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_1_4_fu_183_p2.read()[0].to_bool())? c_flag_1_4_fu_189_p2.read(): p_c_flag_3_fu_176_p3.read());
}

void prefetch::thread_p_c_flag_5_fu_214_p3() {
    p_c_flag_5_fu_214_p3 = (!tmp_1_5_fu_203_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_1_5_fu_203_p2.read()[0].to_bool())? c_flag_1_5_fu_209_p2.read(): p_c_flag_4_reg_341.read());
}

void prefetch::thread_p_c_flag_6_cast_fu_245_p1() {
    p_c_flag_6_cast_fu_245_p1 = esl_zext<4,3>(p_c_flag_6_reg_353.read());
}

void prefetch::thread_p_c_flag_6_fu_232_p3() {
    p_c_flag_6_fu_232_p3 = (!tmp_1_6_fu_221_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_1_6_fu_221_p2.read()[0].to_bool())? c_flag_1_6_fu_227_p2.read(): p_c_flag_5_reg_347.read());
}

void prefetch::thread_p_c_flag_7_fu_254_p3() {
    p_c_flag_7_fu_254_p3 = (!tmp_1_7_reg_358.read()[0].is_01())? sc_lv<4>(): ((tmp_1_7_reg_358.read()[0].to_bool())? c_flag_1_7_fu_248_p2.read(): p_c_flag_6_cast_fu_245_p1.read());
}

void prefetch::thread_p_c_flag_8_fu_273_p3() {
    p_c_flag_8_fu_273_p3 = (!tmp_1_8_fu_261_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_1_8_fu_261_p2.read()[0].to_bool())? c_flag_1_8_fu_267_p2.read(): p_c_flag_7_fu_254_p3.read());
}

void prefetch::thread_p_c_flag_9_fu_292_p3() {
    p_c_flag_9_fu_292_p3 = (!tmp_1_9_fu_281_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_1_9_fu_281_p2.read()[0].to_bool())? c_flag_1_9_fu_287_p2.read(): p_c_flag_8_reg_363.read());
}

void prefetch::thread_p_c_flag_cast_fu_124_p1() {
    p_c_flag_cast_fu_124_p1 = esl_zext<2,1>(tmp_1_reg_320.read());
}

void prefetch::thread_tmp_1_1_fu_118_p2() {
    tmp_1_1_fu_118_p2 = (!reg_88.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_1);
}

void prefetch::thread_tmp_1_2_fu_141_p2() {
    tmp_1_2_fu_141_p2 = (!reg_88.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_2);
}

void prefetch::thread_tmp_1_3_fu_161_p2() {
    tmp_1_3_fu_161_p2 = (!reg_88.read().is_01() || !ap_const_lv32_3.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_3);
}

void prefetch::thread_tmp_1_4_fu_183_p2() {
    tmp_1_4_fu_183_p2 = (!reg_88.read().is_01() || !ap_const_lv32_4.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_4);
}

void prefetch::thread_tmp_1_5_fu_203_p2() {
    tmp_1_5_fu_203_p2 = (!reg_88.read().is_01() || !ap_const_lv32_5.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_5);
}

void prefetch::thread_tmp_1_6_fu_221_p2() {
    tmp_1_6_fu_221_p2 = (!reg_88.read().is_01() || !ap_const_lv32_6.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_6);
}

void prefetch::thread_tmp_1_7_fu_239_p2() {
    tmp_1_7_fu_239_p2 = (!reg_88.read().is_01() || !ap_const_lv32_7.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_7);
}

void prefetch::thread_tmp_1_8_fu_261_p2() {
    tmp_1_8_fu_261_p2 = (!reg_88.read().is_01() || !ap_const_lv32_8.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_8);
}

void prefetch::thread_tmp_1_9_fu_281_p2() {
    tmp_1_9_fu_281_p2 = (!reg_88.read().is_01() || !ap_const_lv32_9.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_9);
}

void prefetch::thread_tmp_1_fu_112_p2() {
    tmp_1_fu_112_p2 = (!reg_88.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(reg_88.read() == ap_const_lv32_0);
}

void prefetch::thread_tmp_2_fu_102_p1() {
    tmp_2_fu_102_p1 = esl_zext<32,30>(source1_reg_309.read());
}

void prefetch::thread_tmp_fu_299_p2() {
    tmp_fu_299_p2 = (!p_c_flag_9_fu_292_p3.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(p_c_flag_9_fu_292_p3.read() == ap_const_lv4_A);
}

void prefetch::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_SOURCE_BUS_ARREADY.read())) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 2048 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 8192 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 16384 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 32768 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 65536 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 131072 : 
            if (!esl_seteq<1,1,1>(SOURCE_BUS_RVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_state18;
            }
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXX";
            break;
    }
}

void prefetch::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"m_axi_SOURCE_BUS_AWVALID\" :  \"" << m_axi_SOURCE_BUS_AWVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWREADY\" :  \"" << m_axi_SOURCE_BUS_AWREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWADDR\" :  \"" << m_axi_SOURCE_BUS_AWADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWID\" :  \"" << m_axi_SOURCE_BUS_AWID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWLEN\" :  \"" << m_axi_SOURCE_BUS_AWLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWSIZE\" :  \"" << m_axi_SOURCE_BUS_AWSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWBURST\" :  \"" << m_axi_SOURCE_BUS_AWBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWLOCK\" :  \"" << m_axi_SOURCE_BUS_AWLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWCACHE\" :  \"" << m_axi_SOURCE_BUS_AWCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWPROT\" :  \"" << m_axi_SOURCE_BUS_AWPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWQOS\" :  \"" << m_axi_SOURCE_BUS_AWQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWREGION\" :  \"" << m_axi_SOURCE_BUS_AWREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_AWUSER\" :  \"" << m_axi_SOURCE_BUS_AWUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_WVALID\" :  \"" << m_axi_SOURCE_BUS_WVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_WREADY\" :  \"" << m_axi_SOURCE_BUS_WREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_WDATA\" :  \"" << m_axi_SOURCE_BUS_WDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_WSTRB\" :  \"" << m_axi_SOURCE_BUS_WSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_WLAST\" :  \"" << m_axi_SOURCE_BUS_WLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_WID\" :  \"" << m_axi_SOURCE_BUS_WID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_WUSER\" :  \"" << m_axi_SOURCE_BUS_WUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARVALID\" :  \"" << m_axi_SOURCE_BUS_ARVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARREADY\" :  \"" << m_axi_SOURCE_BUS_ARREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARADDR\" :  \"" << m_axi_SOURCE_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARID\" :  \"" << m_axi_SOURCE_BUS_ARID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARLEN\" :  \"" << m_axi_SOURCE_BUS_ARLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARSIZE\" :  \"" << m_axi_SOURCE_BUS_ARSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARBURST\" :  \"" << m_axi_SOURCE_BUS_ARBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARLOCK\" :  \"" << m_axi_SOURCE_BUS_ARLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARCACHE\" :  \"" << m_axi_SOURCE_BUS_ARCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARPROT\" :  \"" << m_axi_SOURCE_BUS_ARPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARQOS\" :  \"" << m_axi_SOURCE_BUS_ARQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARREGION\" :  \"" << m_axi_SOURCE_BUS_ARREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_ARUSER\" :  \"" << m_axi_SOURCE_BUS_ARUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_RVALID\" :  \"" << m_axi_SOURCE_BUS_RVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_RREADY\" :  \"" << m_axi_SOURCE_BUS_RREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_RDATA\" :  \"" << m_axi_SOURCE_BUS_RDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_RLAST\" :  \"" << m_axi_SOURCE_BUS_RLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_RID\" :  \"" << m_axi_SOURCE_BUS_RID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_RUSER\" :  \"" << m_axi_SOURCE_BUS_RUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_RRESP\" :  \"" << m_axi_SOURCE_BUS_RRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_BVALID\" :  \"" << m_axi_SOURCE_BUS_BVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_SOURCE_BUS_BREADY\" :  \"" << m_axi_SOURCE_BUS_BREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_BRESP\" :  \"" << m_axi_SOURCE_BUS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_BID\" :  \"" << m_axi_SOURCE_BUS_BID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_SOURCE_BUS_BUSER\" :  \"" << m_axi_SOURCE_BUS_BUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

